// Code generated by ent, DO NOT EDIT.

package department

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldName, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldNote, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v int) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldSort, v))
}

// QuotaUsd applies equality check predicate on the "quota_usd" field. It's identical to QuotaUsdEQ.
func QuotaUsd(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldQuotaUsd, v))
}

// PeriodAnchor applies equality check predicate on the "period_anchor" field. It's identical to PeriodAnchorEQ.
func PeriodAnchor(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldPeriodAnchor, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodUsedBase applies equality check predicate on the "period_used_base" field. It's identical to PeriodUsedBaseEQ.
func PeriodUsedBase(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldPeriodUsedBase, v))
}

// UsedQuota applies equality check predicate on the "used_quota" field. It's identical to UsedQuotaEQ.
func UsedQuota(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldUsedQuota, v))
}

// UsedQuotaActual applies equality check predicate on the "used_quota_actual" field. It's identical to UsedQuotaActualEQ.
func UsedQuotaActual(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldUsedQuotaActual, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Department {
	return predicate.Department(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Department {
	return predicate.Department(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Department {
	return predicate.Department(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Department {
	return predicate.Department(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Department {
	return predicate.Department(sql.FieldContainsFold(FieldName, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Department {
	return predicate.Department(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Department {
	return predicate.Department(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Department {
	return predicate.Department(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Department {
	return predicate.Department(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Department {
	return predicate.Department(sql.FieldContainsFold(FieldNote, v))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v int) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v int) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...int) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...int) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v int) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v int) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v int) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v int) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldSort, v))
}

// QuotaUsdEQ applies the EQ predicate on the "quota_usd" field.
func QuotaUsdEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldQuotaUsd, v))
}

// QuotaUsdNEQ applies the NEQ predicate on the "quota_usd" field.
func QuotaUsdNEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldQuotaUsd, v))
}

// QuotaUsdIn applies the In predicate on the "quota_usd" field.
func QuotaUsdIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldQuotaUsd, vs...))
}

// QuotaUsdNotIn applies the NotIn predicate on the "quota_usd" field.
func QuotaUsdNotIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldQuotaUsd, vs...))
}

// QuotaUsdGT applies the GT predicate on the "quota_usd" field.
func QuotaUsdGT(v float64) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldQuotaUsd, v))
}

// QuotaUsdGTE applies the GTE predicate on the "quota_usd" field.
func QuotaUsdGTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldQuotaUsd, v))
}

// QuotaUsdLT applies the LT predicate on the "quota_usd" field.
func QuotaUsdLT(v float64) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldQuotaUsd, v))
}

// QuotaUsdLTE applies the LTE predicate on the "quota_usd" field.
func QuotaUsdLTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldQuotaUsd, v))
}

// QuotaPeriodEQ applies the EQ predicate on the "quota_period" field.
func QuotaPeriodEQ(v QuotaPeriod) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldQuotaPeriod, v))
}

// QuotaPeriodNEQ applies the NEQ predicate on the "quota_period" field.
func QuotaPeriodNEQ(v QuotaPeriod) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldQuotaPeriod, v))
}

// QuotaPeriodIn applies the In predicate on the "quota_period" field.
func QuotaPeriodIn(vs ...QuotaPeriod) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldQuotaPeriod, vs...))
}

// QuotaPeriodNotIn applies the NotIn predicate on the "quota_period" field.
func QuotaPeriodNotIn(vs ...QuotaPeriod) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldQuotaPeriod, vs...))
}

// PeriodAnchorEQ applies the EQ predicate on the "period_anchor" field.
func PeriodAnchorEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldPeriodAnchor, v))
}

// PeriodAnchorNEQ applies the NEQ predicate on the "period_anchor" field.
func PeriodAnchorNEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldPeriodAnchor, v))
}

// PeriodAnchorIn applies the In predicate on the "period_anchor" field.
func PeriodAnchorIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldPeriodAnchor, vs...))
}

// PeriodAnchorNotIn applies the NotIn predicate on the "period_anchor" field.
func PeriodAnchorNotIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldPeriodAnchor, vs...))
}

// PeriodAnchorGT applies the GT predicate on the "period_anchor" field.
func PeriodAnchorGT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldPeriodAnchor, v))
}

// PeriodAnchorGTE applies the GTE predicate on the "period_anchor" field.
func PeriodAnchorGTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldPeriodAnchor, v))
}

// PeriodAnchorLT applies the LT predicate on the "period_anchor" field.
func PeriodAnchorLT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldPeriodAnchor, v))
}

// PeriodAnchorLTE applies the LTE predicate on the "period_anchor" field.
func PeriodAnchorLTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldPeriodAnchor, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodUsedBaseEQ applies the EQ predicate on the "period_used_base" field.
func PeriodUsedBaseEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldPeriodUsedBase, v))
}

// PeriodUsedBaseNEQ applies the NEQ predicate on the "period_used_base" field.
func PeriodUsedBaseNEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldPeriodUsedBase, v))
}

// PeriodUsedBaseIn applies the In predicate on the "period_used_base" field.
func PeriodUsedBaseIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldPeriodUsedBase, vs...))
}

// PeriodUsedBaseNotIn applies the NotIn predicate on the "period_used_base" field.
func PeriodUsedBaseNotIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldPeriodUsedBase, vs...))
}

// PeriodUsedBaseGT applies the GT predicate on the "period_used_base" field.
func PeriodUsedBaseGT(v float64) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldPeriodUsedBase, v))
}

// PeriodUsedBaseGTE applies the GTE predicate on the "period_used_base" field.
func PeriodUsedBaseGTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldPeriodUsedBase, v))
}

// PeriodUsedBaseLT applies the LT predicate on the "period_used_base" field.
func PeriodUsedBaseLT(v float64) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldPeriodUsedBase, v))
}

// PeriodUsedBaseLTE applies the LTE predicate on the "period_used_base" field.
func PeriodUsedBaseLTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldPeriodUsedBase, v))
}

// UsedQuotaEQ applies the EQ predicate on the "used_quota" field.
func UsedQuotaEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldUsedQuota, v))
}

// UsedQuotaNEQ applies the NEQ predicate on the "used_quota" field.
func UsedQuotaNEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldUsedQuota, v))
}

// UsedQuotaIn applies the In predicate on the "used_quota" field.
func UsedQuotaIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldUsedQuota, vs...))
}

// UsedQuotaNotIn applies the NotIn predicate on the "used_quota" field.
func UsedQuotaNotIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldUsedQuota, vs...))
}

// UsedQuotaGT applies the GT predicate on the "used_quota" field.
func UsedQuotaGT(v float64) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldUsedQuota, v))
}

// UsedQuotaGTE applies the GTE predicate on the "used_quota" field.
func UsedQuotaGTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldUsedQuota, v))
}

// UsedQuotaLT applies the LT predicate on the "used_quota" field.
func UsedQuotaLT(v float64) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldUsedQuota, v))
}

// UsedQuotaLTE applies the LTE predicate on the "used_quota" field.
func UsedQuotaLTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldUsedQuota, v))
}

// UsedQuotaActualEQ applies the EQ predicate on the "used_quota_actual" field.
func UsedQuotaActualEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldUsedQuotaActual, v))
}

// UsedQuotaActualNEQ applies the NEQ predicate on the "used_quota_actual" field.
func UsedQuotaActualNEQ(v float64) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldUsedQuotaActual, v))
}

// UsedQuotaActualIn applies the In predicate on the "used_quota_actual" field.
func UsedQuotaActualIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldUsedQuotaActual, vs...))
}

// UsedQuotaActualNotIn applies the NotIn predicate on the "used_quota_actual" field.
func UsedQuotaActualNotIn(vs ...float64) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldUsedQuotaActual, vs...))
}

// UsedQuotaActualGT applies the GT predicate on the "used_quota_actual" field.
func UsedQuotaActualGT(v float64) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldUsedQuotaActual, v))
}

// UsedQuotaActualGTE applies the GTE predicate on the "used_quota_actual" field.
func UsedQuotaActualGTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldUsedQuotaActual, v))
}

// UsedQuotaActualLT applies the LT predicate on the "used_quota_actual" field.
func UsedQuotaActualLT(v float64) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldUsedQuotaActual, v))
}

// UsedQuotaActualLTE applies the LTE predicate on the "used_quota_actual" field.
func UsedQuotaActualLTE(v float64) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldUsedQuotaActual, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Department {
	return predicate.Department(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Department {
	return predicate.Department(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMembers applies the HasEdge predicate on the "members" edge.
func HasMembers() predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMembersWith applies the HasEdge predicate on the "members" edge with a given conditions (other predicates).
func HasMembersWith(preds ...predicate.Member) predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := newMembersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasManager applies the HasEdge predicate on the "manager" edge.
func HasManager() predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ManagerTable, ManagerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasManagerWith applies the HasEdge predicate on the "manager" edge with a given conditions (other predicates).
func HasManagerWith(preds ...predicate.Member) predicate.Department {
	return predicate.Department(func(s *sql.Selector) {
		step := newManagerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Department) predicate.Department {
	return predicate.Department(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Department) predicate.Department {
	return predicate.Department(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Department) predicate.Department {
	return predicate.Department(sql.NotPredicates(p))
}
