// Code generated by ent, DO NOT EDIT.

package teamauditlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldID, id))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldOwnerID, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldActorUserID, v))
}

// ActorEmail applies equality check predicate on the "actor_email" field. It's identical to ActorEmailEQ.
func ActorEmail(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldActorEmail, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldAction, v))
}

// TargetType applies equality check predicate on the "target_type" field. It's identical to TargetTypeEQ.
func TargetType(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldTargetType, v))
}

// TargetID applies equality check predicate on the "target_id" field. It's identical to TargetIDEQ.
func TargetID(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldTargetID, v))
}

// TargetName applies equality check predicate on the "target_name" field. It's identical to TargetNameEQ.
func TargetName(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldTargetName, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldIP, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldRequestID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldOwnerID, vs...))
}

// OwnerIDGT applies the GT predicate on the "owner_id" field.
func OwnerIDGT(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldOwnerID, v))
}

// OwnerIDGTE applies the GTE predicate on the "owner_id" field.
func OwnerIDGTE(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldOwnerID, v))
}

// OwnerIDLT applies the LT predicate on the "owner_id" field.
func OwnerIDLT(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldOwnerID, v))
}

// OwnerIDLTE applies the LTE predicate on the "owner_id" field.
func OwnerIDLTE(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldOwnerID, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldActorUserID, v))
}

// ActorEmailEQ applies the EQ predicate on the "actor_email" field.
func ActorEmailEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldActorEmail, v))
}

// ActorEmailNEQ applies the NEQ predicate on the "actor_email" field.
func ActorEmailNEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldActorEmail, v))
}

// ActorEmailIn applies the In predicate on the "actor_email" field.
func ActorEmailIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldActorEmail, vs...))
}

// ActorEmailNotIn applies the NotIn predicate on the "actor_email" field.
func ActorEmailNotIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldActorEmail, vs...))
}

// ActorEmailGT applies the GT predicate on the "actor_email" field.
func ActorEmailGT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldActorEmail, v))
}

// ActorEmailGTE applies the GTE predicate on the "actor_email" field.
func ActorEmailGTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldActorEmail, v))
}

// ActorEmailLT applies the LT predicate on the "actor_email" field.
func ActorEmailLT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldActorEmail, v))
}

// ActorEmailLTE applies the LTE predicate on the "actor_email" field.
func ActorEmailLTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldActorEmail, v))
}

// ActorEmailContains applies the Contains predicate on the "actor_email" field.
func ActorEmailContains(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContains(FieldActorEmail, v))
}

// ActorEmailHasPrefix applies the HasPrefix predicate on the "actor_email" field.
func ActorEmailHasPrefix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasPrefix(FieldActorEmail, v))
}

// ActorEmailHasSuffix applies the HasSuffix predicate on the "actor_email" field.
func ActorEmailHasSuffix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasSuffix(FieldActorEmail, v))
}

// ActorEmailEqualFold applies the EqualFold predicate on the "actor_email" field.
func ActorEmailEqualFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEqualFold(FieldActorEmail, v))
}

// ActorEmailContainsFold applies the ContainsFold predicate on the "actor_email" field.
func ActorEmailContainsFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContainsFold(FieldActorEmail, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContainsFold(FieldAction, v))
}

// TargetTypeEQ applies the EQ predicate on the "target_type" field.
func TargetTypeEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldTargetType, v))
}

// TargetTypeNEQ applies the NEQ predicate on the "target_type" field.
func TargetTypeNEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldTargetType, v))
}

// TargetTypeIn applies the In predicate on the "target_type" field.
func TargetTypeIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldTargetType, vs...))
}

// TargetTypeNotIn applies the NotIn predicate on the "target_type" field.
func TargetTypeNotIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldTargetType, vs...))
}

// TargetTypeGT applies the GT predicate on the "target_type" field.
func TargetTypeGT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldTargetType, v))
}

// TargetTypeGTE applies the GTE predicate on the "target_type" field.
func TargetTypeGTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldTargetType, v))
}

// TargetTypeLT applies the LT predicate on the "target_type" field.
func TargetTypeLT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldTargetType, v))
}

// TargetTypeLTE applies the LTE predicate on the "target_type" field.
func TargetTypeLTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldTargetType, v))
}

// TargetTypeContains applies the Contains predicate on the "target_type" field.
func TargetTypeContains(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContains(FieldTargetType, v))
}

// TargetTypeHasPrefix applies the HasPrefix predicate on the "target_type" field.
func TargetTypeHasPrefix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasPrefix(FieldTargetType, v))
}

// TargetTypeHasSuffix applies the HasSuffix predicate on the "target_type" field.
func TargetTypeHasSuffix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasSuffix(FieldTargetType, v))
}

// TargetTypeEqualFold applies the EqualFold predicate on the "target_type" field.
func TargetTypeEqualFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEqualFold(FieldTargetType, v))
}

// TargetTypeContainsFold applies the ContainsFold predicate on the "target_type" field.
func TargetTypeContainsFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContainsFold(FieldTargetType, v))
}

// TargetIDEQ applies the EQ predicate on the "target_id" field.
func TargetIDEQ(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldTargetID, v))
}

// TargetIDNEQ applies the NEQ predicate on the "target_id" field.
func TargetIDNEQ(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldTargetID, v))
}

// TargetIDIn applies the In predicate on the "target_id" field.
func TargetIDIn(vs ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldTargetID, vs...))
}

// TargetIDNotIn applies the NotIn predicate on the "target_id" field.
func TargetIDNotIn(vs ...int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldTargetID, vs...))
}

// TargetIDGT applies the GT predicate on the "target_id" field.
func TargetIDGT(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldTargetID, v))
}

// TargetIDGTE applies the GTE predicate on the "target_id" field.
func TargetIDGTE(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldTargetID, v))
}

// TargetIDLT applies the LT predicate on the "target_id" field.
func TargetIDLT(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldTargetID, v))
}

// TargetIDLTE applies the LTE predicate on the "target_id" field.
func TargetIDLTE(v int) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldTargetID, v))
}

// TargetNameEQ applies the EQ predicate on the "target_name" field.
func TargetNameEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldTargetName, v))
}

// TargetNameNEQ applies the NEQ predicate on the "target_name" field.
func TargetNameNEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldTargetName, v))
}

// TargetNameIn applies the In predicate on the "target_name" field.
func TargetNameIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldTargetName, vs...))
}

// TargetNameNotIn applies the NotIn predicate on the "target_name" field.
func TargetNameNotIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldTargetName, vs...))
}

// TargetNameGT applies the GT predicate on the "target_name" field.
func TargetNameGT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldTargetName, v))
}

// TargetNameGTE applies the GTE predicate on the "target_name" field.
func TargetNameGTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldTargetName, v))
}

// TargetNameLT applies the LT predicate on the "target_name" field.
func TargetNameLT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldTargetName, v))
}

// TargetNameLTE applies the LTE predicate on the "target_name" field.
func TargetNameLTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldTargetName, v))
}

// TargetNameContains applies the Contains predicate on the "target_name" field.
func TargetNameContains(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContains(FieldTargetName, v))
}

// TargetNameHasPrefix applies the HasPrefix predicate on the "target_name" field.
func TargetNameHasPrefix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasPrefix(FieldTargetName, v))
}

// TargetNameHasSuffix applies the HasSuffix predicate on the "target_name" field.
func TargetNameHasSuffix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasSuffix(FieldTargetName, v))
}

// TargetNameEqualFold applies the EqualFold predicate on the "target_name" field.
func TargetNameEqualFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEqualFold(FieldTargetName, v))
}

// TargetNameContainsFold applies the ContainsFold predicate on the "target_name" field.
func TargetNameContainsFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContainsFold(FieldTargetName, v))
}

// BeforeIsNil applies the IsNil predicate on the "before" field.
func BeforeIsNil() predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIsNull(FieldBefore))
}

// BeforeNotNil applies the NotNil predicate on the "before" field.
func BeforeNotNil() predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotNull(FieldBefore))
}

// AfterIsNil applies the IsNil predicate on the "after" field.
func AfterIsNil() predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIsNull(FieldAfter))
}

// AfterNotNil applies the NotNil predicate on the "after" field.
func AfterNotNil() predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotNull(FieldAfter))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContainsFold(FieldIP, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldContainsFold(FieldRequestID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamAuditLog) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamAuditLog) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamAuditLog) predicate.TeamAuditLog {
	return predicate.TeamAuditLog(sql.NotPredicates(p))
}
