// Code generated by ent, DO NOT EDIT.

package usagelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldID, id))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldPlatform, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
}

// InputTokens applies equality check predicate on the "input_tokens" field. It's identical to InputTokensEQ.
func InputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
}

// OutputTokens applies equality check predicate on the "output_tokens" field. It's identical to OutputTokensEQ.
func OutputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
}

// CachedInputTokens applies equality check predicate on the "cached_input_tokens" field. It's identical to CachedInputTokensEQ.
func CachedInputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputTokens, v))
}

// CacheCreationTokens applies equality check predicate on the "cache_creation_tokens" field. It's identical to CacheCreationTokensEQ.
func CacheCreationTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreation5mTokens applies equality check predicate on the "cache_creation_5m_tokens" field. It's identical to CacheCreation5mTokensEQ.
func CacheCreation5mTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation5mTokens, v))
}

// CacheCreation1hTokens applies equality check predicate on the "cache_creation_1h_tokens" field. It's identical to CacheCreation1hTokensEQ.
func CacheCreation1hTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation1hTokens, v))
}

// ReasoningOutputTokens applies equality check predicate on the "reasoning_output_tokens" field. It's identical to ReasoningOutputTokensEQ.
func ReasoningOutputTokens(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldReasoningOutputTokens, v))
}

// InputPrice applies equality check predicate on the "input_price" field. It's identical to InputPriceEQ.
func InputPrice(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputPrice, v))
}

// OutputPrice applies equality check predicate on the "output_price" field. It's identical to OutputPriceEQ.
func OutputPrice(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputPrice, v))
}

// CachedInputPrice applies equality check predicate on the "cached_input_price" field. It's identical to CachedInputPriceEQ.
func CachedInputPrice(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputPrice, v))
}

// CacheCreationPrice applies equality check predicate on the "cache_creation_price" field. It's identical to CacheCreationPriceEQ.
func CacheCreationPrice(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationPrice, v))
}

// CacheCreation1hPrice applies equality check predicate on the "cache_creation_1h_price" field. It's identical to CacheCreation1hPriceEQ.
func CacheCreation1hPrice(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation1hPrice, v))
}

// InputCost applies equality check predicate on the "input_cost" field. It's identical to InputCostEQ.
func InputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
}

// OutputCost applies equality check predicate on the "output_cost" field. It's identical to OutputCostEQ.
func OutputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
}

// CachedInputCost applies equality check predicate on the "cached_input_cost" field. It's identical to CachedInputCostEQ.
func CachedInputCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputCost, v))
}

// CacheCreationCost applies equality check predicate on the "cache_creation_cost" field. It's identical to CacheCreationCostEQ.
func CacheCreationCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationCost, v))
}

// ImageCost applies equality check predicate on the "image_cost" field. It's identical to ImageCostEQ.
func ImageCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageCost, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldActualCost, v))
}

// BilledCost applies equality check predicate on the "billed_cost" field. It's identical to BilledCostEQ.
func BilledCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldBilledCost, v))
}

// AccountCost applies equality check predicate on the "account_cost" field. It's identical to AccountCostEQ.
func AccountCost(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountCost, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
}

// SellRate applies equality check predicate on the "sell_rate" field. It's identical to SellRateEQ.
func SellRate(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldSellRate, v))
}

// AccountRateMultiplier applies equality check predicate on the "account_rate_multiplier" field. It's identical to AccountRateMultiplierEQ.
func AccountRateMultiplier(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountRateMultiplier, v))
}

// ServiceTier applies equality check predicate on the "service_tier" field. It's identical to ServiceTierEQ.
func ServiceTier(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldServiceTier, v))
}

// ImageSize applies equality check predicate on the "image_size" field. It's identical to ImageSizeEQ.
func ImageSize(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageSize, v))
}

// Stream applies equality check predicate on the "stream" field. It's identical to StreamEQ.
func Stream(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// FirstTokenMs applies equality check predicate on the "first_token_ms" field. It's identical to FirstTokenMsEQ.
func FirstTokenMs(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
}

// IPAddress applies equality check predicate on the "ip_address" field. It's identical to IPAddressEQ.
func IPAddress(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
}

// Endpoint applies equality check predicate on the "endpoint" field. It's identical to EndpointEQ.
func Endpoint(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldEndpoint, v))
}

// ReasoningEffort applies equality check predicate on the "reasoning_effort" field. It's identical to ReasoningEffortEQ.
func ReasoningEffort(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldReasoningEffort, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRequestID, v))
}

// UserIDSnapshot applies equality check predicate on the "user_id_snapshot" field. It's identical to UserIDSnapshotEQ.
func UserIDSnapshot(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserIDSnapshot, v))
}

// UserEmailSnapshot applies equality check predicate on the "user_email_snapshot" field. It's identical to UserEmailSnapshotEQ.
func UserEmailSnapshot(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserEmailSnapshot, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStatus, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorStatus applies equality check predicate on the "error_status" field. It's identical to ErrorStatusEQ.
func ErrorStatus(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorStatus, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldPlatform, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldModel, v))
}

// InputTokensEQ applies the EQ predicate on the "input_tokens" field.
func InputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputTokens, v))
}

// InputTokensNEQ applies the NEQ predicate on the "input_tokens" field.
func InputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputTokens, v))
}

// InputTokensIn applies the In predicate on the "input_tokens" field.
func InputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputTokens, vs...))
}

// InputTokensNotIn applies the NotIn predicate on the "input_tokens" field.
func InputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputTokens, vs...))
}

// InputTokensGT applies the GT predicate on the "input_tokens" field.
func InputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputTokens, v))
}

// InputTokensGTE applies the GTE predicate on the "input_tokens" field.
func InputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputTokens, v))
}

// InputTokensLT applies the LT predicate on the "input_tokens" field.
func InputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputTokens, v))
}

// InputTokensLTE applies the LTE predicate on the "input_tokens" field.
func InputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputTokens, v))
}

// OutputTokensEQ applies the EQ predicate on the "output_tokens" field.
func OutputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputTokens, v))
}

// OutputTokensNEQ applies the NEQ predicate on the "output_tokens" field.
func OutputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputTokens, v))
}

// OutputTokensIn applies the In predicate on the "output_tokens" field.
func OutputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputTokens, vs...))
}

// OutputTokensNotIn applies the NotIn predicate on the "output_tokens" field.
func OutputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputTokens, vs...))
}

// OutputTokensGT applies the GT predicate on the "output_tokens" field.
func OutputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputTokens, v))
}

// OutputTokensGTE applies the GTE predicate on the "output_tokens" field.
func OutputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputTokens, v))
}

// OutputTokensLT applies the LT predicate on the "output_tokens" field.
func OutputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputTokens, v))
}

// OutputTokensLTE applies the LTE predicate on the "output_tokens" field.
func OutputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputTokens, v))
}

// CachedInputTokensEQ applies the EQ predicate on the "cached_input_tokens" field.
func CachedInputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputTokens, v))
}

// CachedInputTokensNEQ applies the NEQ predicate on the "cached_input_tokens" field.
func CachedInputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCachedInputTokens, v))
}

// CachedInputTokensIn applies the In predicate on the "cached_input_tokens" field.
func CachedInputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCachedInputTokens, vs...))
}

// CachedInputTokensNotIn applies the NotIn predicate on the "cached_input_tokens" field.
func CachedInputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCachedInputTokens, vs...))
}

// CachedInputTokensGT applies the GT predicate on the "cached_input_tokens" field.
func CachedInputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCachedInputTokens, v))
}

// CachedInputTokensGTE applies the GTE predicate on the "cached_input_tokens" field.
func CachedInputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCachedInputTokens, v))
}

// CachedInputTokensLT applies the LT predicate on the "cached_input_tokens" field.
func CachedInputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCachedInputTokens, v))
}

// CachedInputTokensLTE applies the LTE predicate on the "cached_input_tokens" field.
func CachedInputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCachedInputTokens, v))
}

// CacheCreationTokensEQ applies the EQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensNEQ applies the NEQ predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreationTokens, v))
}

// CacheCreationTokensIn applies the In predicate on the "cache_creation_tokens" field.
func CacheCreationTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensNotIn applies the NotIn predicate on the "cache_creation_tokens" field.
func CacheCreationTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreationTokens, vs...))
}

// CacheCreationTokensGT applies the GT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensGTE applies the GTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLT applies the LT predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreationTokens, v))
}

// CacheCreationTokensLTE applies the LTE predicate on the "cache_creation_tokens" field.
func CacheCreationTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreationTokens, v))
}

// CacheCreation5mTokensEQ applies the EQ predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensNEQ applies the NEQ predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensIn applies the In predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreation5mTokens, vs...))
}

// CacheCreation5mTokensNotIn applies the NotIn predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreation5mTokens, vs...))
}

// CacheCreation5mTokensGT applies the GT predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensGTE applies the GTE predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensLT applies the LT predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreation5mTokens, v))
}

// CacheCreation5mTokensLTE applies the LTE predicate on the "cache_creation_5m_tokens" field.
func CacheCreation5mTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreation5mTokens, v))
}

// CacheCreation1hTokensEQ applies the EQ predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensNEQ applies the NEQ predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensIn applies the In predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreation1hTokens, vs...))
}

// CacheCreation1hTokensNotIn applies the NotIn predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreation1hTokens, vs...))
}

// CacheCreation1hTokensGT applies the GT predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensGTE applies the GTE predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensLT applies the LT predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreation1hTokens, v))
}

// CacheCreation1hTokensLTE applies the LTE predicate on the "cache_creation_1h_tokens" field.
func CacheCreation1hTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreation1hTokens, v))
}

// ReasoningOutputTokensEQ applies the EQ predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensNEQ applies the NEQ predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensIn applies the In predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldReasoningOutputTokens, vs...))
}

// ReasoningOutputTokensNotIn applies the NotIn predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldReasoningOutputTokens, vs...))
}

// ReasoningOutputTokensGT applies the GT predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensGTE applies the GTE predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensLT applies the LT predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldReasoningOutputTokens, v))
}

// ReasoningOutputTokensLTE applies the LTE predicate on the "reasoning_output_tokens" field.
func ReasoningOutputTokensLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldReasoningOutputTokens, v))
}

// InputPriceEQ applies the EQ predicate on the "input_price" field.
func InputPriceEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputPrice, v))
}

// InputPriceNEQ applies the NEQ predicate on the "input_price" field.
func InputPriceNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputPrice, v))
}

// InputPriceIn applies the In predicate on the "input_price" field.
func InputPriceIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputPrice, vs...))
}

// InputPriceNotIn applies the NotIn predicate on the "input_price" field.
func InputPriceNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputPrice, vs...))
}

// InputPriceGT applies the GT predicate on the "input_price" field.
func InputPriceGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputPrice, v))
}

// InputPriceGTE applies the GTE predicate on the "input_price" field.
func InputPriceGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputPrice, v))
}

// InputPriceLT applies the LT predicate on the "input_price" field.
func InputPriceLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputPrice, v))
}

// InputPriceLTE applies the LTE predicate on the "input_price" field.
func InputPriceLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputPrice, v))
}

// OutputPriceEQ applies the EQ predicate on the "output_price" field.
func OutputPriceEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputPrice, v))
}

// OutputPriceNEQ applies the NEQ predicate on the "output_price" field.
func OutputPriceNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputPrice, v))
}

// OutputPriceIn applies the In predicate on the "output_price" field.
func OutputPriceIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputPrice, vs...))
}

// OutputPriceNotIn applies the NotIn predicate on the "output_price" field.
func OutputPriceNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputPrice, vs...))
}

// OutputPriceGT applies the GT predicate on the "output_price" field.
func OutputPriceGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputPrice, v))
}

// OutputPriceGTE applies the GTE predicate on the "output_price" field.
func OutputPriceGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputPrice, v))
}

// OutputPriceLT applies the LT predicate on the "output_price" field.
func OutputPriceLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputPrice, v))
}

// OutputPriceLTE applies the LTE predicate on the "output_price" field.
func OutputPriceLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputPrice, v))
}

// CachedInputPriceEQ applies the EQ predicate on the "cached_input_price" field.
func CachedInputPriceEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputPrice, v))
}

// CachedInputPriceNEQ applies the NEQ predicate on the "cached_input_price" field.
func CachedInputPriceNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCachedInputPrice, v))
}

// CachedInputPriceIn applies the In predicate on the "cached_input_price" field.
func CachedInputPriceIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCachedInputPrice, vs...))
}

// CachedInputPriceNotIn applies the NotIn predicate on the "cached_input_price" field.
func CachedInputPriceNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCachedInputPrice, vs...))
}

// CachedInputPriceGT applies the GT predicate on the "cached_input_price" field.
func CachedInputPriceGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCachedInputPrice, v))
}

// CachedInputPriceGTE applies the GTE predicate on the "cached_input_price" field.
func CachedInputPriceGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCachedInputPrice, v))
}

// CachedInputPriceLT applies the LT predicate on the "cached_input_price" field.
func CachedInputPriceLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCachedInputPrice, v))
}

// CachedInputPriceLTE applies the LTE predicate on the "cached_input_price" field.
func CachedInputPriceLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCachedInputPrice, v))
}

// CacheCreationPriceEQ applies the EQ predicate on the "cache_creation_price" field.
func CacheCreationPriceEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationPrice, v))
}

// CacheCreationPriceNEQ applies the NEQ predicate on the "cache_creation_price" field.
func CacheCreationPriceNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreationPrice, v))
}

// CacheCreationPriceIn applies the In predicate on the "cache_creation_price" field.
func CacheCreationPriceIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreationPrice, vs...))
}

// CacheCreationPriceNotIn applies the NotIn predicate on the "cache_creation_price" field.
func CacheCreationPriceNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreationPrice, vs...))
}

// CacheCreationPriceGT applies the GT predicate on the "cache_creation_price" field.
func CacheCreationPriceGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreationPrice, v))
}

// CacheCreationPriceGTE applies the GTE predicate on the "cache_creation_price" field.
func CacheCreationPriceGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreationPrice, v))
}

// CacheCreationPriceLT applies the LT predicate on the "cache_creation_price" field.
func CacheCreationPriceLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreationPrice, v))
}

// CacheCreationPriceLTE applies the LTE predicate on the "cache_creation_price" field.
func CacheCreationPriceLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreationPrice, v))
}

// CacheCreation1hPriceEQ applies the EQ predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreation1hPrice, v))
}

// CacheCreation1hPriceNEQ applies the NEQ predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreation1hPrice, v))
}

// CacheCreation1hPriceIn applies the In predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreation1hPrice, vs...))
}

// CacheCreation1hPriceNotIn applies the NotIn predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreation1hPrice, vs...))
}

// CacheCreation1hPriceGT applies the GT predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreation1hPrice, v))
}

// CacheCreation1hPriceGTE applies the GTE predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreation1hPrice, v))
}

// CacheCreation1hPriceLT applies the LT predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreation1hPrice, v))
}

// CacheCreation1hPriceLTE applies the LTE predicate on the "cache_creation_1h_price" field.
func CacheCreation1hPriceLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreation1hPrice, v))
}

// InputCostEQ applies the EQ predicate on the "input_cost" field.
func InputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldInputCost, v))
}

// InputCostNEQ applies the NEQ predicate on the "input_cost" field.
func InputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldInputCost, v))
}

// InputCostIn applies the In predicate on the "input_cost" field.
func InputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldInputCost, vs...))
}

// InputCostNotIn applies the NotIn predicate on the "input_cost" field.
func InputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldInputCost, vs...))
}

// InputCostGT applies the GT predicate on the "input_cost" field.
func InputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldInputCost, v))
}

// InputCostGTE applies the GTE predicate on the "input_cost" field.
func InputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldInputCost, v))
}

// InputCostLT applies the LT predicate on the "input_cost" field.
func InputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldInputCost, v))
}

// InputCostLTE applies the LTE predicate on the "input_cost" field.
func InputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldInputCost, v))
}

// OutputCostEQ applies the EQ predicate on the "output_cost" field.
func OutputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldOutputCost, v))
}

// OutputCostNEQ applies the NEQ predicate on the "output_cost" field.
func OutputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldOutputCost, v))
}

// OutputCostIn applies the In predicate on the "output_cost" field.
func OutputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldOutputCost, vs...))
}

// OutputCostNotIn applies the NotIn predicate on the "output_cost" field.
func OutputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldOutputCost, vs...))
}

// OutputCostGT applies the GT predicate on the "output_cost" field.
func OutputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldOutputCost, v))
}

// OutputCostGTE applies the GTE predicate on the "output_cost" field.
func OutputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldOutputCost, v))
}

// OutputCostLT applies the LT predicate on the "output_cost" field.
func OutputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldOutputCost, v))
}

// OutputCostLTE applies the LTE predicate on the "output_cost" field.
func OutputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldOutputCost, v))
}

// CachedInputCostEQ applies the EQ predicate on the "cached_input_cost" field.
func CachedInputCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCachedInputCost, v))
}

// CachedInputCostNEQ applies the NEQ predicate on the "cached_input_cost" field.
func CachedInputCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCachedInputCost, v))
}

// CachedInputCostIn applies the In predicate on the "cached_input_cost" field.
func CachedInputCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCachedInputCost, vs...))
}

// CachedInputCostNotIn applies the NotIn predicate on the "cached_input_cost" field.
func CachedInputCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCachedInputCost, vs...))
}

// CachedInputCostGT applies the GT predicate on the "cached_input_cost" field.
func CachedInputCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCachedInputCost, v))
}

// CachedInputCostGTE applies the GTE predicate on the "cached_input_cost" field.
func CachedInputCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCachedInputCost, v))
}

// CachedInputCostLT applies the LT predicate on the "cached_input_cost" field.
func CachedInputCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCachedInputCost, v))
}

// CachedInputCostLTE applies the LTE predicate on the "cached_input_cost" field.
func CachedInputCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCachedInputCost, v))
}

// CacheCreationCostEQ applies the EQ predicate on the "cache_creation_cost" field.
func CacheCreationCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCacheCreationCost, v))
}

// CacheCreationCostNEQ applies the NEQ predicate on the "cache_creation_cost" field.
func CacheCreationCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCacheCreationCost, v))
}

// CacheCreationCostIn applies the In predicate on the "cache_creation_cost" field.
func CacheCreationCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCacheCreationCost, vs...))
}

// CacheCreationCostNotIn applies the NotIn predicate on the "cache_creation_cost" field.
func CacheCreationCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCacheCreationCost, vs...))
}

// CacheCreationCostGT applies the GT predicate on the "cache_creation_cost" field.
func CacheCreationCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCacheCreationCost, v))
}

// CacheCreationCostGTE applies the GTE predicate on the "cache_creation_cost" field.
func CacheCreationCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCacheCreationCost, v))
}

// CacheCreationCostLT applies the LT predicate on the "cache_creation_cost" field.
func CacheCreationCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCacheCreationCost, v))
}

// CacheCreationCostLTE applies the LTE predicate on the "cache_creation_cost" field.
func CacheCreationCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCacheCreationCost, v))
}

// ImageCostEQ applies the EQ predicate on the "image_cost" field.
func ImageCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageCost, v))
}

// ImageCostNEQ applies the NEQ predicate on the "image_cost" field.
func ImageCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldImageCost, v))
}

// ImageCostIn applies the In predicate on the "image_cost" field.
func ImageCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldImageCost, vs...))
}

// ImageCostNotIn applies the NotIn predicate on the "image_cost" field.
func ImageCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldImageCost, vs...))
}

// ImageCostGT applies the GT predicate on the "image_cost" field.
func ImageCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldImageCost, v))
}

// ImageCostGTE applies the GTE predicate on the "image_cost" field.
func ImageCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldImageCost, v))
}

// ImageCostLT applies the LT predicate on the "image_cost" field.
func ImageCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldImageCost, v))
}

// ImageCostLTE applies the LTE predicate on the "image_cost" field.
func ImageCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldImageCost, v))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldTotalCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldActualCost, v))
}

// BilledCostEQ applies the EQ predicate on the "billed_cost" field.
func BilledCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldBilledCost, v))
}

// BilledCostNEQ applies the NEQ predicate on the "billed_cost" field.
func BilledCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldBilledCost, v))
}

// BilledCostIn applies the In predicate on the "billed_cost" field.
func BilledCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldBilledCost, vs...))
}

// BilledCostNotIn applies the NotIn predicate on the "billed_cost" field.
func BilledCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldBilledCost, vs...))
}

// BilledCostGT applies the GT predicate on the "billed_cost" field.
func BilledCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldBilledCost, v))
}

// BilledCostGTE applies the GTE predicate on the "billed_cost" field.
func BilledCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldBilledCost, v))
}

// BilledCostLT applies the LT predicate on the "billed_cost" field.
func BilledCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldBilledCost, v))
}

// BilledCostLTE applies the LTE predicate on the "billed_cost" field.
func BilledCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldBilledCost, v))
}

// AccountCostEQ applies the EQ predicate on the "account_cost" field.
func AccountCostEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountCost, v))
}

// AccountCostNEQ applies the NEQ predicate on the "account_cost" field.
func AccountCostNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldAccountCost, v))
}

// AccountCostIn applies the In predicate on the "account_cost" field.
func AccountCostIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldAccountCost, vs...))
}

// AccountCostNotIn applies the NotIn predicate on the "account_cost" field.
func AccountCostNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldAccountCost, vs...))
}

// AccountCostGT applies the GT predicate on the "account_cost" field.
func AccountCostGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldAccountCost, v))
}

// AccountCostGTE applies the GTE predicate on the "account_cost" field.
func AccountCostGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldAccountCost, v))
}

// AccountCostLT applies the LT predicate on the "account_cost" field.
func AccountCostLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldAccountCost, v))
}

// AccountCostLTE applies the LTE predicate on the "account_cost" field.
func AccountCostLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldAccountCost, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldRateMultiplier, v))
}

// SellRateEQ applies the EQ predicate on the "sell_rate" field.
func SellRateEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldSellRate, v))
}

// SellRateNEQ applies the NEQ predicate on the "sell_rate" field.
func SellRateNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldSellRate, v))
}

// SellRateIn applies the In predicate on the "sell_rate" field.
func SellRateIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldSellRate, vs...))
}

// SellRateNotIn applies the NotIn predicate on the "sell_rate" field.
func SellRateNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldSellRate, vs...))
}

// SellRateGT applies the GT predicate on the "sell_rate" field.
func SellRateGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldSellRate, v))
}

// SellRateGTE applies the GTE predicate on the "sell_rate" field.
func SellRateGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldSellRate, v))
}

// SellRateLT applies the LT predicate on the "sell_rate" field.
func SellRateLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldSellRate, v))
}

// SellRateLTE applies the LTE predicate on the "sell_rate" field.
func SellRateLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldSellRate, v))
}

// AccountRateMultiplierEQ applies the EQ predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierNEQ applies the NEQ predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierNEQ(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierIn applies the In predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldAccountRateMultiplier, vs...))
}

// AccountRateMultiplierNotIn applies the NotIn predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierNotIn(vs ...float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldAccountRateMultiplier, vs...))
}

// AccountRateMultiplierGT applies the GT predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierGT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierGTE applies the GTE predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierGTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierLT applies the LT predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierLT(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierLTE applies the LTE predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierLTE(v float64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldAccountRateMultiplier, v))
}

// ServiceTierEQ applies the EQ predicate on the "service_tier" field.
func ServiceTierEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldServiceTier, v))
}

// ServiceTierNEQ applies the NEQ predicate on the "service_tier" field.
func ServiceTierNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldServiceTier, v))
}

// ServiceTierIn applies the In predicate on the "service_tier" field.
func ServiceTierIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldServiceTier, vs...))
}

// ServiceTierNotIn applies the NotIn predicate on the "service_tier" field.
func ServiceTierNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldServiceTier, vs...))
}

// ServiceTierGT applies the GT predicate on the "service_tier" field.
func ServiceTierGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldServiceTier, v))
}

// ServiceTierGTE applies the GTE predicate on the "service_tier" field.
func ServiceTierGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldServiceTier, v))
}

// ServiceTierLT applies the LT predicate on the "service_tier" field.
func ServiceTierLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldServiceTier, v))
}

// ServiceTierLTE applies the LTE predicate on the "service_tier" field.
func ServiceTierLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldServiceTier, v))
}

// ServiceTierContains applies the Contains predicate on the "service_tier" field.
func ServiceTierContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldServiceTier, v))
}

// ServiceTierHasPrefix applies the HasPrefix predicate on the "service_tier" field.
func ServiceTierHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldServiceTier, v))
}

// ServiceTierHasSuffix applies the HasSuffix predicate on the "service_tier" field.
func ServiceTierHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldServiceTier, v))
}

// ServiceTierEqualFold applies the EqualFold predicate on the "service_tier" field.
func ServiceTierEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldServiceTier, v))
}

// ServiceTierContainsFold applies the ContainsFold predicate on the "service_tier" field.
func ServiceTierContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldServiceTier, v))
}

// ImageSizeEQ applies the EQ predicate on the "image_size" field.
func ImageSizeEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldImageSize, v))
}

// ImageSizeNEQ applies the NEQ predicate on the "image_size" field.
func ImageSizeNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldImageSize, v))
}

// ImageSizeIn applies the In predicate on the "image_size" field.
func ImageSizeIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldImageSize, vs...))
}

// ImageSizeNotIn applies the NotIn predicate on the "image_size" field.
func ImageSizeNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldImageSize, vs...))
}

// ImageSizeGT applies the GT predicate on the "image_size" field.
func ImageSizeGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldImageSize, v))
}

// ImageSizeGTE applies the GTE predicate on the "image_size" field.
func ImageSizeGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldImageSize, v))
}

// ImageSizeLT applies the LT predicate on the "image_size" field.
func ImageSizeLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldImageSize, v))
}

// ImageSizeLTE applies the LTE predicate on the "image_size" field.
func ImageSizeLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldImageSize, v))
}

// ImageSizeContains applies the Contains predicate on the "image_size" field.
func ImageSizeContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldImageSize, v))
}

// ImageSizeHasPrefix applies the HasPrefix predicate on the "image_size" field.
func ImageSizeHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldImageSize, v))
}

// ImageSizeHasSuffix applies the HasSuffix predicate on the "image_size" field.
func ImageSizeHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldImageSize, v))
}

// ImageSizeEqualFold applies the EqualFold predicate on the "image_size" field.
func ImageSizeEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldImageSize, v))
}

// ImageSizeContainsFold applies the ContainsFold predicate on the "image_size" field.
func ImageSizeContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldImageSize, v))
}

// StreamEQ applies the EQ predicate on the "stream" field.
func StreamEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStream, v))
}

// StreamNEQ applies the NEQ predicate on the "stream" field.
func StreamNEQ(v bool) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldStream, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldDurationMs, v))
}

// FirstTokenMsEQ applies the EQ predicate on the "first_token_ms" field.
func FirstTokenMsEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsNEQ applies the NEQ predicate on the "first_token_ms" field.
func FirstTokenMsNEQ(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldFirstTokenMs, v))
}

// FirstTokenMsIn applies the In predicate on the "first_token_ms" field.
func FirstTokenMsIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsNotIn applies the NotIn predicate on the "first_token_ms" field.
func FirstTokenMsNotIn(vs ...int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldFirstTokenMs, vs...))
}

// FirstTokenMsGT applies the GT predicate on the "first_token_ms" field.
func FirstTokenMsGT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldFirstTokenMs, v))
}

// FirstTokenMsGTE applies the GTE predicate on the "first_token_ms" field.
func FirstTokenMsGTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldFirstTokenMs, v))
}

// FirstTokenMsLT applies the LT predicate on the "first_token_ms" field.
func FirstTokenMsLT(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldFirstTokenMs, v))
}

// FirstTokenMsLTE applies the LTE predicate on the "first_token_ms" field.
func FirstTokenMsLTE(v int64) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldFirstTokenMs, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldUserAgent, v))
}

// IPAddressEQ applies the EQ predicate on the "ip_address" field.
func IPAddressEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldIPAddress, v))
}

// IPAddressNEQ applies the NEQ predicate on the "ip_address" field.
func IPAddressNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldIPAddress, v))
}

// IPAddressIn applies the In predicate on the "ip_address" field.
func IPAddressIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldIPAddress, vs...))
}

// IPAddressNotIn applies the NotIn predicate on the "ip_address" field.
func IPAddressNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldIPAddress, vs...))
}

// IPAddressGT applies the GT predicate on the "ip_address" field.
func IPAddressGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldIPAddress, v))
}

// IPAddressGTE applies the GTE predicate on the "ip_address" field.
func IPAddressGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldIPAddress, v))
}

// IPAddressLT applies the LT predicate on the "ip_address" field.
func IPAddressLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldIPAddress, v))
}

// IPAddressLTE applies the LTE predicate on the "ip_address" field.
func IPAddressLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldIPAddress, v))
}

// IPAddressContains applies the Contains predicate on the "ip_address" field.
func IPAddressContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldIPAddress, v))
}

// IPAddressHasPrefix applies the HasPrefix predicate on the "ip_address" field.
func IPAddressHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldIPAddress, v))
}

// IPAddressHasSuffix applies the HasSuffix predicate on the "ip_address" field.
func IPAddressHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldIPAddress, v))
}

// IPAddressEqualFold applies the EqualFold predicate on the "ip_address" field.
func IPAddressEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldIPAddress, v))
}

// IPAddressContainsFold applies the ContainsFold predicate on the "ip_address" field.
func IPAddressContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldIPAddress, v))
}

// EndpointEQ applies the EQ predicate on the "endpoint" field.
func EndpointEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldEndpoint, v))
}

// EndpointNEQ applies the NEQ predicate on the "endpoint" field.
func EndpointNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldEndpoint, v))
}

// EndpointIn applies the In predicate on the "endpoint" field.
func EndpointIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldEndpoint, vs...))
}

// EndpointNotIn applies the NotIn predicate on the "endpoint" field.
func EndpointNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldEndpoint, vs...))
}

// EndpointGT applies the GT predicate on the "endpoint" field.
func EndpointGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldEndpoint, v))
}

// EndpointGTE applies the GTE predicate on the "endpoint" field.
func EndpointGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldEndpoint, v))
}

// EndpointLT applies the LT predicate on the "endpoint" field.
func EndpointLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldEndpoint, v))
}

// EndpointLTE applies the LTE predicate on the "endpoint" field.
func EndpointLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldEndpoint, v))
}

// EndpointContains applies the Contains predicate on the "endpoint" field.
func EndpointContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldEndpoint, v))
}

// EndpointHasPrefix applies the HasPrefix predicate on the "endpoint" field.
func EndpointHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldEndpoint, v))
}

// EndpointHasSuffix applies the HasSuffix predicate on the "endpoint" field.
func EndpointHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldEndpoint, v))
}

// EndpointEqualFold applies the EqualFold predicate on the "endpoint" field.
func EndpointEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldEndpoint, v))
}

// EndpointContainsFold applies the ContainsFold predicate on the "endpoint" field.
func EndpointContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldEndpoint, v))
}

// ReasoningEffortEQ applies the EQ predicate on the "reasoning_effort" field.
func ReasoningEffortEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldReasoningEffort, v))
}

// ReasoningEffortNEQ applies the NEQ predicate on the "reasoning_effort" field.
func ReasoningEffortNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldReasoningEffort, v))
}

// ReasoningEffortIn applies the In predicate on the "reasoning_effort" field.
func ReasoningEffortIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortNotIn applies the NotIn predicate on the "reasoning_effort" field.
func ReasoningEffortNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortGT applies the GT predicate on the "reasoning_effort" field.
func ReasoningEffortGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldReasoningEffort, v))
}

// ReasoningEffortGTE applies the GTE predicate on the "reasoning_effort" field.
func ReasoningEffortGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldReasoningEffort, v))
}

// ReasoningEffortLT applies the LT predicate on the "reasoning_effort" field.
func ReasoningEffortLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldReasoningEffort, v))
}

// ReasoningEffortLTE applies the LTE predicate on the "reasoning_effort" field.
func ReasoningEffortLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldReasoningEffort, v))
}

// ReasoningEffortContains applies the Contains predicate on the "reasoning_effort" field.
func ReasoningEffortContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldReasoningEffort, v))
}

// ReasoningEffortHasPrefix applies the HasPrefix predicate on the "reasoning_effort" field.
func ReasoningEffortHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldReasoningEffort, v))
}

// ReasoningEffortHasSuffix applies the HasSuffix predicate on the "reasoning_effort" field.
func ReasoningEffortHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldReasoningEffort, v))
}

// ReasoningEffortEqualFold applies the EqualFold predicate on the "reasoning_effort" field.
func ReasoningEffortEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldReasoningEffort, v))
}

// ReasoningEffortContainsFold applies the ContainsFold predicate on the "reasoning_effort" field.
func ReasoningEffortContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldReasoningEffort, v))
}

// UsageAttributesIsNil applies the IsNil predicate on the "usage_attributes" field.
func UsageAttributesIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldUsageAttributes))
}

// UsageAttributesNotNil applies the NotNil predicate on the "usage_attributes" field.
func UsageAttributesNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldUsageAttributes))
}

// UsageMetricsIsNil applies the IsNil predicate on the "usage_metrics" field.
func UsageMetricsIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldUsageMetrics))
}

// UsageMetricsNotNil applies the NotNil predicate on the "usage_metrics" field.
func UsageMetricsNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldUsageMetrics))
}

// UsageCostDetailsIsNil applies the IsNil predicate on the "usage_cost_details" field.
func UsageCostDetailsIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldUsageCostDetails))
}

// UsageCostDetailsNotNil applies the NotNil predicate on the "usage_cost_details" field.
func UsageCostDetailsNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldUsageCostDetails))
}

// UsageMetadataIsNil applies the IsNil predicate on the "usage_metadata" field.
func UsageMetadataIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldUsageMetadata))
}

// UsageMetadataNotNil applies the NotNil predicate on the "usage_metadata" field.
func UsageMetadataNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldUsageMetadata))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldRequestID, v))
}

// UserIDSnapshotEQ applies the EQ predicate on the "user_id_snapshot" field.
func UserIDSnapshotEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserIDSnapshot, v))
}

// UserIDSnapshotNEQ applies the NEQ predicate on the "user_id_snapshot" field.
func UserIDSnapshotNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserIDSnapshot, v))
}

// UserIDSnapshotIn applies the In predicate on the "user_id_snapshot" field.
func UserIDSnapshotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserIDSnapshot, vs...))
}

// UserIDSnapshotNotIn applies the NotIn predicate on the "user_id_snapshot" field.
func UserIDSnapshotNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserIDSnapshot, vs...))
}

// UserIDSnapshotGT applies the GT predicate on the "user_id_snapshot" field.
func UserIDSnapshotGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldUserIDSnapshot, v))
}

// UserIDSnapshotGTE applies the GTE predicate on the "user_id_snapshot" field.
func UserIDSnapshotGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldUserIDSnapshot, v))
}

// UserIDSnapshotLT applies the LT predicate on the "user_id_snapshot" field.
func UserIDSnapshotLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldUserIDSnapshot, v))
}

// UserIDSnapshotLTE applies the LTE predicate on the "user_id_snapshot" field.
func UserIDSnapshotLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldUserIDSnapshot, v))
}

// UserEmailSnapshotEQ applies the EQ predicate on the "user_email_snapshot" field.
func UserEmailSnapshotEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotNEQ applies the NEQ predicate on the "user_email_snapshot" field.
func UserEmailSnapshotNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotIn applies the In predicate on the "user_email_snapshot" field.
func UserEmailSnapshotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldUserEmailSnapshot, vs...))
}

// UserEmailSnapshotNotIn applies the NotIn predicate on the "user_email_snapshot" field.
func UserEmailSnapshotNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldUserEmailSnapshot, vs...))
}

// UserEmailSnapshotGT applies the GT predicate on the "user_email_snapshot" field.
func UserEmailSnapshotGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotGTE applies the GTE predicate on the "user_email_snapshot" field.
func UserEmailSnapshotGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotLT applies the LT predicate on the "user_email_snapshot" field.
func UserEmailSnapshotLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotLTE applies the LTE predicate on the "user_email_snapshot" field.
func UserEmailSnapshotLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotContains applies the Contains predicate on the "user_email_snapshot" field.
func UserEmailSnapshotContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotHasPrefix applies the HasPrefix predicate on the "user_email_snapshot" field.
func UserEmailSnapshotHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotHasSuffix applies the HasSuffix predicate on the "user_email_snapshot" field.
func UserEmailSnapshotHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotEqualFold applies the EqualFold predicate on the "user_email_snapshot" field.
func UserEmailSnapshotEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldUserEmailSnapshot, v))
}

// UserEmailSnapshotContainsFold applies the ContainsFold predicate on the "user_email_snapshot" field.
func UserEmailSnapshotContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldUserEmailSnapshot, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldStatus, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldErrorCode, v))
}

// ErrorStatusEQ applies the EQ predicate on the "error_status" field.
func ErrorStatusEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorStatus, v))
}

// ErrorStatusNEQ applies the NEQ predicate on the "error_status" field.
func ErrorStatusNEQ(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldErrorStatus, v))
}

// ErrorStatusIn applies the In predicate on the "error_status" field.
func ErrorStatusIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldErrorStatus, vs...))
}

// ErrorStatusNotIn applies the NotIn predicate on the "error_status" field.
func ErrorStatusNotIn(vs ...int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldErrorStatus, vs...))
}

// ErrorStatusGT applies the GT predicate on the "error_status" field.
func ErrorStatusGT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldErrorStatus, v))
}

// ErrorStatusGTE applies the GTE predicate on the "error_status" field.
func ErrorStatusGTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldErrorStatus, v))
}

// ErrorStatusLT applies the LT predicate on the "error_status" field.
func ErrorStatusLT(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldErrorStatus, v))
}

// ErrorStatusLTE applies the LTE predicate on the "error_status" field.
func ErrorStatusLTE(v int) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldErrorStatus, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLog {
	return predicate.UsageLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.UsageLog {
	return predicate.UsageLog(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLog) predicate.UsageLog {
	return predicate.UsageLog(sql.NotPredicates(p))
}
