// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/account"
	"github.com/DouDOU-start/airgate-core/ent/accountevent"
)

// AccountEvent is the model entity for the AccountEvent schema.
type AccountEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType accountevent.EventType `json:"event_type,omitempty"`
	// 事件原因（forwarder 判决 Reason / 管理操作说明），写入前截断
	Reason string `json:"reason,omitempty"`
	// 家族级冷却时的模型家族键（如 gpt-image），账号级事件为空
	Family string `json:"family,omitempty"`
	// 事件来源：forward（转发判决）/ probe（配额巡检）/ manual（管理员操作）
	Source string `json:"source,omitempty"`
	// 上游 HTTP 状态码，无则为 0
	UpstreamStatus int `json:"upstream_status,omitempty"`
	// 触发本次事件请求的终端用户 ID（转发判决链路）；探测/手动/无用户上下文为 0。修复后据此定位要通知的用户
	UserID int `json:"user_id,omitempty"`
	// 触发本次事件请求所用的 API Key ID；无则为 0
	APIKeyID int `json:"api_key_id,omitempty"`
	// rate_limited / degraded 的冷却到期时间
	StateUntil *time.Time `json:"state_until,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountEventQuery when eager-loading is set.
	Edges          AccountEventEdges `json:"edges"`
	account_events *int
	selectValues   sql.SelectValues
}

// AccountEventEdges holds the relations/edges for other nodes in the graph.
type AccountEventEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEventEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountevent.FieldID, accountevent.FieldUpstreamStatus, accountevent.FieldUserID, accountevent.FieldAPIKeyID:
			values[i] = new(sql.NullInt64)
		case accountevent.FieldEventType, accountevent.FieldReason, accountevent.FieldFamily, accountevent.FieldSource:
			values[i] = new(sql.NullString)
		case accountevent.FieldStateUntil, accountevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case accountevent.ForeignKeys[0]: // account_events
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountEvent fields.
func (ae *AccountEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ae.ID = int(value.Int64)
		case accountevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				ae.EventType = accountevent.EventType(value.String)
			}
		case accountevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				ae.Reason = value.String
			}
		case accountevent.FieldFamily:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field family", values[i])
			} else if value.Valid {
				ae.Family = value.String
			}
		case accountevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				ae.Source = value.String
			}
		case accountevent.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				ae.UpstreamStatus = int(value.Int64)
			}
		case accountevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ae.UserID = int(value.Int64)
			}
		case accountevent.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				ae.APIKeyID = int(value.Int64)
			}
		case accountevent.FieldStateUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field state_until", values[i])
			} else if value.Valid {
				ae.StateUntil = new(time.Time)
				*ae.StateUntil = value.Time
			}
		case accountevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ae.CreatedAt = value.Time
			}
		case accountevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field account_events", value)
			} else if value.Valid {
				ae.account_events = new(int)
				*ae.account_events = int(value.Int64)
			}
		default:
			ae.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountEvent.
// This includes values selected through modifiers, order, etc.
func (ae *AccountEvent) Value(name string) (ent.Value, error) {
	return ae.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the AccountEvent entity.
func (ae *AccountEvent) QueryAccount() *AccountQuery {
	return NewAccountEventClient(ae.config).QueryAccount(ae)
}

// Update returns a builder for updating this AccountEvent.
// Note that you need to call AccountEvent.Unwrap() before calling this method if this AccountEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ae *AccountEvent) Update() *AccountEventUpdateOne {
	return NewAccountEventClient(ae.config).UpdateOne(ae)
}

// Unwrap unwraps the AccountEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ae *AccountEvent) Unwrap() *AccountEvent {
	_tx, ok := ae.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountEvent is not a transactional entity")
	}
	ae.config.driver = _tx.drv
	return ae
}

// String implements the fmt.Stringer.
func (ae *AccountEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AccountEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ae.ID))
	builder.WriteString("event_type=")
	builder.WriteString(fmt.Sprintf("%v", ae.EventType))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(ae.Reason)
	builder.WriteString(", ")
	builder.WriteString("family=")
	builder.WriteString(ae.Family)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(ae.Source)
	builder.WriteString(", ")
	builder.WriteString("upstream_status=")
	builder.WriteString(fmt.Sprintf("%v", ae.UpstreamStatus))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.APIKeyID))
	builder.WriteString(", ")
	if v := ae.StateUntil; v != nil {
		builder.WriteString("state_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ae.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountEvents is a parsable slice of AccountEvent.
type AccountEvents []*AccountEvent
