// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/balancelog"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// BalanceLogUpdate is the builder for updating BalanceLog entities.
type BalanceLogUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceLogMutation
}

// Where appends a list predicates to the BalanceLogUpdate builder.
func (blu *BalanceLogUpdate) Where(ps ...predicate.BalanceLog) *BalanceLogUpdate {
	blu.mutation.Where(ps...)
	return blu
}

// SetAction sets the "action" field.
func (blu *BalanceLogUpdate) SetAction(b balancelog.Action) *BalanceLogUpdate {
	blu.mutation.SetAction(b)
	return blu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableAction(b *balancelog.Action) *BalanceLogUpdate {
	if b != nil {
		blu.SetAction(*b)
	}
	return blu
}

// SetAmount sets the "amount" field.
func (blu *BalanceLogUpdate) SetAmount(f float64) *BalanceLogUpdate {
	blu.mutation.ResetAmount()
	blu.mutation.SetAmount(f)
	return blu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableAmount(f *float64) *BalanceLogUpdate {
	if f != nil {
		blu.SetAmount(*f)
	}
	return blu
}

// AddAmount adds f to the "amount" field.
func (blu *BalanceLogUpdate) AddAmount(f float64) *BalanceLogUpdate {
	blu.mutation.AddAmount(f)
	return blu
}

// SetBeforeBalance sets the "before_balance" field.
func (blu *BalanceLogUpdate) SetBeforeBalance(f float64) *BalanceLogUpdate {
	blu.mutation.ResetBeforeBalance()
	blu.mutation.SetBeforeBalance(f)
	return blu
}

// SetNillableBeforeBalance sets the "before_balance" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableBeforeBalance(f *float64) *BalanceLogUpdate {
	if f != nil {
		blu.SetBeforeBalance(*f)
	}
	return blu
}

// AddBeforeBalance adds f to the "before_balance" field.
func (blu *BalanceLogUpdate) AddBeforeBalance(f float64) *BalanceLogUpdate {
	blu.mutation.AddBeforeBalance(f)
	return blu
}

// SetAfterBalance sets the "after_balance" field.
func (blu *BalanceLogUpdate) SetAfterBalance(f float64) *BalanceLogUpdate {
	blu.mutation.ResetAfterBalance()
	blu.mutation.SetAfterBalance(f)
	return blu
}

// SetNillableAfterBalance sets the "after_balance" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableAfterBalance(f *float64) *BalanceLogUpdate {
	if f != nil {
		blu.SetAfterBalance(*f)
	}
	return blu
}

// AddAfterBalance adds f to the "after_balance" field.
func (blu *BalanceLogUpdate) AddAfterBalance(f float64) *BalanceLogUpdate {
	blu.mutation.AddAfterBalance(f)
	return blu
}

// SetRemark sets the "remark" field.
func (blu *BalanceLogUpdate) SetRemark(s string) *BalanceLogUpdate {
	blu.mutation.SetRemark(s)
	return blu
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableRemark(s *string) *BalanceLogUpdate {
	if s != nil {
		blu.SetRemark(*s)
	}
	return blu
}

// SetUserIDSnapshot sets the "user_id_snapshot" field.
func (blu *BalanceLogUpdate) SetUserIDSnapshot(i int) *BalanceLogUpdate {
	blu.mutation.ResetUserIDSnapshot()
	blu.mutation.SetUserIDSnapshot(i)
	return blu
}

// SetNillableUserIDSnapshot sets the "user_id_snapshot" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableUserIDSnapshot(i *int) *BalanceLogUpdate {
	if i != nil {
		blu.SetUserIDSnapshot(*i)
	}
	return blu
}

// AddUserIDSnapshot adds i to the "user_id_snapshot" field.
func (blu *BalanceLogUpdate) AddUserIDSnapshot(i int) *BalanceLogUpdate {
	blu.mutation.AddUserIDSnapshot(i)
	return blu
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (blu *BalanceLogUpdate) SetUserEmailSnapshot(s string) *BalanceLogUpdate {
	blu.mutation.SetUserEmailSnapshot(s)
	return blu
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableUserEmailSnapshot(s *string) *BalanceLogUpdate {
	if s != nil {
		blu.SetUserEmailSnapshot(*s)
	}
	return blu
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (blu *BalanceLogUpdate) SetIdempotencyKey(s string) *BalanceLogUpdate {
	blu.mutation.SetIdempotencyKey(s)
	return blu
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableIdempotencyKey(s *string) *BalanceLogUpdate {
	if s != nil {
		blu.SetIdempotencyKey(*s)
	}
	return blu
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (blu *BalanceLogUpdate) ClearIdempotencyKey() *BalanceLogUpdate {
	blu.mutation.ClearIdempotencyKey()
	return blu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (blu *BalanceLogUpdate) SetUserID(id int) *BalanceLogUpdate {
	blu.mutation.SetUserID(id)
	return blu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (blu *BalanceLogUpdate) SetNillableUserID(id *int) *BalanceLogUpdate {
	if id != nil {
		blu = blu.SetUserID(*id)
	}
	return blu
}

// SetUser sets the "user" edge to the User entity.
func (blu *BalanceLogUpdate) SetUser(u *User) *BalanceLogUpdate {
	return blu.SetUserID(u.ID)
}

// Mutation returns the BalanceLogMutation object of the builder.
func (blu *BalanceLogUpdate) Mutation() *BalanceLogMutation {
	return blu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (blu *BalanceLogUpdate) ClearUser() *BalanceLogUpdate {
	blu.mutation.ClearUser()
	return blu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (blu *BalanceLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, blu.sqlSave, blu.mutation, blu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (blu *BalanceLogUpdate) SaveX(ctx context.Context) int {
	affected, err := blu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (blu *BalanceLogUpdate) Exec(ctx context.Context) error {
	_, err := blu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (blu *BalanceLogUpdate) ExecX(ctx context.Context) {
	if err := blu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (blu *BalanceLogUpdate) check() error {
	if v, ok := blu.mutation.Action(); ok {
		if err := balancelog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.action": %w`, err)}
		}
	}
	return nil
}

func (blu *BalanceLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := blu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancelog.Table, balancelog.Columns, sqlgraph.NewFieldSpec(balancelog.FieldID, field.TypeInt))
	if ps := blu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := blu.mutation.Action(); ok {
		_spec.SetField(balancelog.FieldAction, field.TypeEnum, value)
	}
	if value, ok := blu.mutation.Amount(); ok {
		_spec.SetField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := blu.mutation.AddedAmount(); ok {
		_spec.AddField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := blu.mutation.BeforeBalance(); ok {
		_spec.SetField(balancelog.FieldBeforeBalance, field.TypeFloat64, value)
	}
	if value, ok := blu.mutation.AddedBeforeBalance(); ok {
		_spec.AddField(balancelog.FieldBeforeBalance, field.TypeFloat64, value)
	}
	if value, ok := blu.mutation.AfterBalance(); ok {
		_spec.SetField(balancelog.FieldAfterBalance, field.TypeFloat64, value)
	}
	if value, ok := blu.mutation.AddedAfterBalance(); ok {
		_spec.AddField(balancelog.FieldAfterBalance, field.TypeFloat64, value)
	}
	if value, ok := blu.mutation.Remark(); ok {
		_spec.SetField(balancelog.FieldRemark, field.TypeString, value)
	}
	if value, ok := blu.mutation.UserIDSnapshot(); ok {
		_spec.SetField(balancelog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := blu.mutation.AddedUserIDSnapshot(); ok {
		_spec.AddField(balancelog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := blu.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(balancelog.FieldUserEmailSnapshot, field.TypeString, value)
	}
	if value, ok := blu.mutation.IdempotencyKey(); ok {
		_spec.SetField(balancelog.FieldIdempotencyKey, field.TypeString, value)
	}
	if blu.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(balancelog.FieldIdempotencyKey, field.TypeString)
	}
	if blu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := blu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, blu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	blu.mutation.done = true
	return n, nil
}

// BalanceLogUpdateOne is the builder for updating a single BalanceLog entity.
type BalanceLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceLogMutation
}

// SetAction sets the "action" field.
func (bluo *BalanceLogUpdateOne) SetAction(b balancelog.Action) *BalanceLogUpdateOne {
	bluo.mutation.SetAction(b)
	return bluo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableAction(b *balancelog.Action) *BalanceLogUpdateOne {
	if b != nil {
		bluo.SetAction(*b)
	}
	return bluo
}

// SetAmount sets the "amount" field.
func (bluo *BalanceLogUpdateOne) SetAmount(f float64) *BalanceLogUpdateOne {
	bluo.mutation.ResetAmount()
	bluo.mutation.SetAmount(f)
	return bluo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableAmount(f *float64) *BalanceLogUpdateOne {
	if f != nil {
		bluo.SetAmount(*f)
	}
	return bluo
}

// AddAmount adds f to the "amount" field.
func (bluo *BalanceLogUpdateOne) AddAmount(f float64) *BalanceLogUpdateOne {
	bluo.mutation.AddAmount(f)
	return bluo
}

// SetBeforeBalance sets the "before_balance" field.
func (bluo *BalanceLogUpdateOne) SetBeforeBalance(f float64) *BalanceLogUpdateOne {
	bluo.mutation.ResetBeforeBalance()
	bluo.mutation.SetBeforeBalance(f)
	return bluo
}

// SetNillableBeforeBalance sets the "before_balance" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableBeforeBalance(f *float64) *BalanceLogUpdateOne {
	if f != nil {
		bluo.SetBeforeBalance(*f)
	}
	return bluo
}

// AddBeforeBalance adds f to the "before_balance" field.
func (bluo *BalanceLogUpdateOne) AddBeforeBalance(f float64) *BalanceLogUpdateOne {
	bluo.mutation.AddBeforeBalance(f)
	return bluo
}

// SetAfterBalance sets the "after_balance" field.
func (bluo *BalanceLogUpdateOne) SetAfterBalance(f float64) *BalanceLogUpdateOne {
	bluo.mutation.ResetAfterBalance()
	bluo.mutation.SetAfterBalance(f)
	return bluo
}

// SetNillableAfterBalance sets the "after_balance" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableAfterBalance(f *float64) *BalanceLogUpdateOne {
	if f != nil {
		bluo.SetAfterBalance(*f)
	}
	return bluo
}

// AddAfterBalance adds f to the "after_balance" field.
func (bluo *BalanceLogUpdateOne) AddAfterBalance(f float64) *BalanceLogUpdateOne {
	bluo.mutation.AddAfterBalance(f)
	return bluo
}

// SetRemark sets the "remark" field.
func (bluo *BalanceLogUpdateOne) SetRemark(s string) *BalanceLogUpdateOne {
	bluo.mutation.SetRemark(s)
	return bluo
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableRemark(s *string) *BalanceLogUpdateOne {
	if s != nil {
		bluo.SetRemark(*s)
	}
	return bluo
}

// SetUserIDSnapshot sets the "user_id_snapshot" field.
func (bluo *BalanceLogUpdateOne) SetUserIDSnapshot(i int) *BalanceLogUpdateOne {
	bluo.mutation.ResetUserIDSnapshot()
	bluo.mutation.SetUserIDSnapshot(i)
	return bluo
}

// SetNillableUserIDSnapshot sets the "user_id_snapshot" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableUserIDSnapshot(i *int) *BalanceLogUpdateOne {
	if i != nil {
		bluo.SetUserIDSnapshot(*i)
	}
	return bluo
}

// AddUserIDSnapshot adds i to the "user_id_snapshot" field.
func (bluo *BalanceLogUpdateOne) AddUserIDSnapshot(i int) *BalanceLogUpdateOne {
	bluo.mutation.AddUserIDSnapshot(i)
	return bluo
}

// SetUserEmailSnapshot sets the "user_email_snapshot" field.
func (bluo *BalanceLogUpdateOne) SetUserEmailSnapshot(s string) *BalanceLogUpdateOne {
	bluo.mutation.SetUserEmailSnapshot(s)
	return bluo
}

// SetNillableUserEmailSnapshot sets the "user_email_snapshot" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableUserEmailSnapshot(s *string) *BalanceLogUpdateOne {
	if s != nil {
		bluo.SetUserEmailSnapshot(*s)
	}
	return bluo
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (bluo *BalanceLogUpdateOne) SetIdempotencyKey(s string) *BalanceLogUpdateOne {
	bluo.mutation.SetIdempotencyKey(s)
	return bluo
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableIdempotencyKey(s *string) *BalanceLogUpdateOne {
	if s != nil {
		bluo.SetIdempotencyKey(*s)
	}
	return bluo
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (bluo *BalanceLogUpdateOne) ClearIdempotencyKey() *BalanceLogUpdateOne {
	bluo.mutation.ClearIdempotencyKey()
	return bluo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (bluo *BalanceLogUpdateOne) SetUserID(id int) *BalanceLogUpdateOne {
	bluo.mutation.SetUserID(id)
	return bluo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (bluo *BalanceLogUpdateOne) SetNillableUserID(id *int) *BalanceLogUpdateOne {
	if id != nil {
		bluo = bluo.SetUserID(*id)
	}
	return bluo
}

// SetUser sets the "user" edge to the User entity.
func (bluo *BalanceLogUpdateOne) SetUser(u *User) *BalanceLogUpdateOne {
	return bluo.SetUserID(u.ID)
}

// Mutation returns the BalanceLogMutation object of the builder.
func (bluo *BalanceLogUpdateOne) Mutation() *BalanceLogMutation {
	return bluo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (bluo *BalanceLogUpdateOne) ClearUser() *BalanceLogUpdateOne {
	bluo.mutation.ClearUser()
	return bluo
}

// Where appends a list predicates to the BalanceLogUpdate builder.
func (bluo *BalanceLogUpdateOne) Where(ps ...predicate.BalanceLog) *BalanceLogUpdateOne {
	bluo.mutation.Where(ps...)
	return bluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (bluo *BalanceLogUpdateOne) Select(field string, fields ...string) *BalanceLogUpdateOne {
	bluo.fields = append([]string{field}, fields...)
	return bluo
}

// Save executes the query and returns the updated BalanceLog entity.
func (bluo *BalanceLogUpdateOne) Save(ctx context.Context) (*BalanceLog, error) {
	return withHooks(ctx, bluo.sqlSave, bluo.mutation, bluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bluo *BalanceLogUpdateOne) SaveX(ctx context.Context) *BalanceLog {
	node, err := bluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (bluo *BalanceLogUpdateOne) Exec(ctx context.Context) error {
	_, err := bluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bluo *BalanceLogUpdateOne) ExecX(ctx context.Context) {
	if err := bluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bluo *BalanceLogUpdateOne) check() error {
	if v, ok := bluo.mutation.Action(); ok {
		if err := balancelog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "BalanceLog.action": %w`, err)}
		}
	}
	return nil
}

func (bluo *BalanceLogUpdateOne) sqlSave(ctx context.Context) (_node *BalanceLog, err error) {
	if err := bluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balancelog.Table, balancelog.Columns, sqlgraph.NewFieldSpec(balancelog.FieldID, field.TypeInt))
	id, ok := bluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := bluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balancelog.FieldID)
		for _, f := range fields {
			if !balancelog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balancelog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := bluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bluo.mutation.Action(); ok {
		_spec.SetField(balancelog.FieldAction, field.TypeEnum, value)
	}
	if value, ok := bluo.mutation.Amount(); ok {
		_spec.SetField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := bluo.mutation.AddedAmount(); ok {
		_spec.AddField(balancelog.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := bluo.mutation.BeforeBalance(); ok {
		_spec.SetField(balancelog.FieldBeforeBalance, field.TypeFloat64, value)
	}
	if value, ok := bluo.mutation.AddedBeforeBalance(); ok {
		_spec.AddField(balancelog.FieldBeforeBalance, field.TypeFloat64, value)
	}
	if value, ok := bluo.mutation.AfterBalance(); ok {
		_spec.SetField(balancelog.FieldAfterBalance, field.TypeFloat64, value)
	}
	if value, ok := bluo.mutation.AddedAfterBalance(); ok {
		_spec.AddField(balancelog.FieldAfterBalance, field.TypeFloat64, value)
	}
	if value, ok := bluo.mutation.Remark(); ok {
		_spec.SetField(balancelog.FieldRemark, field.TypeString, value)
	}
	if value, ok := bluo.mutation.UserIDSnapshot(); ok {
		_spec.SetField(balancelog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := bluo.mutation.AddedUserIDSnapshot(); ok {
		_spec.AddField(balancelog.FieldUserIDSnapshot, field.TypeInt, value)
	}
	if value, ok := bluo.mutation.UserEmailSnapshot(); ok {
		_spec.SetField(balancelog.FieldUserEmailSnapshot, field.TypeString, value)
	}
	if value, ok := bluo.mutation.IdempotencyKey(); ok {
		_spec.SetField(balancelog.FieldIdempotencyKey, field.TypeString, value)
	}
	if bluo.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(balancelog.FieldIdempotencyKey, field.TypeString)
	}
	if bluo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bluo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   balancelog.UserTable,
			Columns: []string{balancelog.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BalanceLog{config: bluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, bluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balancelog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	bluo.mutation.done = true
	return _node, nil
}
