// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/balancelog"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// BalanceLog is the model entity for the BalanceLog schema.
type BalanceLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Action holds the value of the "action" field.
	Action balancelog.Action `json:"action,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// BeforeBalance holds the value of the "before_balance" field.
	BeforeBalance float64 `json:"before_balance,omitempty"`
	// AfterBalance holds the value of the "after_balance" field.
	AfterBalance float64 `json:"after_balance,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// 用户 ID 快照。用户硬删除后保留余额流水归属。
	UserIDSnapshot int `json:"user_id_snapshot,omitempty"`
	// 用户邮箱快照。用户硬删除后保留余额流水归属。
	UserEmailSnapshot string `json:"user_email_snapshot,omitempty"`
	// 幂等键。插件经 user.update_balance 入账时防重复；NULL 表示无幂等要求。
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BalanceLogQuery when eager-loading is set.
	Edges             BalanceLogEdges `json:"edges"`
	user_balance_logs *int
	selectValues      sql.SelectValues
}

// BalanceLogEdges holds the relations/edges for other nodes in the graph.
type BalanceLogEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BalanceLogEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balancelog.FieldAmount, balancelog.FieldBeforeBalance, balancelog.FieldAfterBalance:
			values[i] = new(sql.NullFloat64)
		case balancelog.FieldID, balancelog.FieldUserIDSnapshot:
			values[i] = new(sql.NullInt64)
		case balancelog.FieldAction, balancelog.FieldRemark, balancelog.FieldUserEmailSnapshot, balancelog.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case balancelog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case balancelog.ForeignKeys[0]: // user_balance_logs
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceLog fields.
func (bl *BalanceLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balancelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			bl.ID = int(value.Int64)
		case balancelog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				bl.Action = balancelog.Action(value.String)
			}
		case balancelog.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				bl.Amount = value.Float64
			}
		case balancelog.FieldBeforeBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field before_balance", values[i])
			} else if value.Valid {
				bl.BeforeBalance = value.Float64
			}
		case balancelog.FieldAfterBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field after_balance", values[i])
			} else if value.Valid {
				bl.AfterBalance = value.Float64
			}
		case balancelog.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				bl.Remark = value.String
			}
		case balancelog.FieldUserIDSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id_snapshot", values[i])
			} else if value.Valid {
				bl.UserIDSnapshot = int(value.Int64)
			}
		case balancelog.FieldUserEmailSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_email_snapshot", values[i])
			} else if value.Valid {
				bl.UserEmailSnapshot = value.String
			}
		case balancelog.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				bl.IdempotencyKey = new(string)
				*bl.IdempotencyKey = value.String
			}
		case balancelog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				bl.CreatedAt = value.Time
			}
		case balancelog.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_balance_logs", value)
			} else if value.Valid {
				bl.user_balance_logs = new(int)
				*bl.user_balance_logs = int(value.Int64)
			}
		default:
			bl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalanceLog.
// This includes values selected through modifiers, order, etc.
func (bl *BalanceLog) Value(name string) (ent.Value, error) {
	return bl.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the BalanceLog entity.
func (bl *BalanceLog) QueryUser() *UserQuery {
	return NewBalanceLogClient(bl.config).QueryUser(bl)
}

// Update returns a builder for updating this BalanceLog.
// Note that you need to call BalanceLog.Unwrap() before calling this method if this BalanceLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (bl *BalanceLog) Update() *BalanceLogUpdateOne {
	return NewBalanceLogClient(bl.config).UpdateOne(bl)
}

// Unwrap unwraps the BalanceLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bl *BalanceLog) Unwrap() *BalanceLog {
	_tx, ok := bl.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceLog is not a transactional entity")
	}
	bl.config.driver = _tx.drv
	return bl
}

// String implements the fmt.Stringer.
func (bl *BalanceLog) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", bl.ID))
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", bl.Action))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", bl.Amount))
	builder.WriteString(", ")
	builder.WriteString("before_balance=")
	builder.WriteString(fmt.Sprintf("%v", bl.BeforeBalance))
	builder.WriteString(", ")
	builder.WriteString("after_balance=")
	builder.WriteString(fmt.Sprintf("%v", bl.AfterBalance))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(bl.Remark)
	builder.WriteString(", ")
	builder.WriteString("user_id_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", bl.UserIDSnapshot))
	builder.WriteString(", ")
	builder.WriteString("user_email_snapshot=")
	builder.WriteString(bl.UserEmailSnapshot)
	builder.WriteString(", ")
	if v := bl.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(bl.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BalanceLogs is a parsable slice of BalanceLog.
type BalanceLogs []*BalanceLog
