// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/department"
	"github.com/DouDOU-start/airgate-core/ent/user"
)

// Department is the model entity for the Department schema.
type Department struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Note holds the value of the "note" field.
	Note string `json:"note,omitempty"`
	// Sort holds the value of the "sort" field.
	Sort int `json:"sort,omitempty"`
	// 部门额度（USD 账面口径，与 members.quota_usd 同源）。0 表示不限。
	QuotaUsd float64 `json:"quota_usd,omitempty"`
	// 额度周期：none=一次性总额；monthly=按月重置（以 period_anchor 逐月对齐、月末夹紧）。
	QuotaPeriod department.QuotaPeriod `json:"quota_period,omitempty"`
	// 月度换期锚点，继承企业账期锚点；换期日与它同日对齐。
	PeriodAnchor time.Time `json:"period_anchor,omitempty"`
	// 当前计量期起点。monthly 时惰性推进；none 时仅记录最近一次手动重置。
	PeriodStart time.Time `json:"period_start,omitempty"`
	// 本期起点时 used_quota 的快照。本期已用 = used_quota − period_used_base。
	PeriodUsedBase float64 `json:"period_used_base,omitempty"`
	// 累计账面已用：累加 billed_cost（与 members.used_quota 同口径）。
	UsedQuota float64 `json:"used_quota,omitempty"`
	// 累计真实成本：累加 actual_cost，即企业主为该部门实际付出的余额。
	UsedQuotaActual float64 `json:"used_quota_actual,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DepartmentQuery when eager-loading is set.
	Edges            DepartmentEdges `json:"edges"`
	user_departments *int
	selectValues     sql.SelectValues
}

// DepartmentEdges holds the relations/edges for other nodes in the graph.
type DepartmentEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Members holds the value of the members edge.
	Members []*Member `json:"members,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DepartmentEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) MembersOrErr() ([]*Member, error) {
	if e.loadedTypes[1] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e DepartmentEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[2] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Department) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case department.FieldQuotaUsd, department.FieldPeriodUsedBase, department.FieldUsedQuota, department.FieldUsedQuotaActual:
			values[i] = new(sql.NullFloat64)
		case department.FieldID, department.FieldSort:
			values[i] = new(sql.NullInt64)
		case department.FieldName, department.FieldNote, department.FieldQuotaPeriod:
			values[i] = new(sql.NullString)
		case department.FieldPeriodAnchor, department.FieldPeriodStart, department.FieldCreatedAt, department.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case department.ForeignKeys[0]: // user_departments
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Department fields.
func (d *Department) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case department.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			d.ID = int(value.Int64)
		case department.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				d.Name = value.String
			}
		case department.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				d.Note = value.String
			}
		case department.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				d.Sort = int(value.Int64)
			}
		case department.FieldQuotaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_usd", values[i])
			} else if value.Valid {
				d.QuotaUsd = value.Float64
			}
		case department.FieldQuotaPeriod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quota_period", values[i])
			} else if value.Valid {
				d.QuotaPeriod = department.QuotaPeriod(value.String)
			}
		case department.FieldPeriodAnchor:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_anchor", values[i])
			} else if value.Valid {
				d.PeriodAnchor = value.Time
			}
		case department.FieldPeriodStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field period_start", values[i])
			} else if value.Valid {
				d.PeriodStart = value.Time
			}
		case department.FieldPeriodUsedBase:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field period_used_base", values[i])
			} else if value.Valid {
				d.PeriodUsedBase = value.Float64
			}
		case department.FieldUsedQuota:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_quota", values[i])
			} else if value.Valid {
				d.UsedQuota = value.Float64
			}
		case department.FieldUsedQuotaActual:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_quota_actual", values[i])
			} else if value.Valid {
				d.UsedQuotaActual = value.Float64
			}
		case department.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				d.CreatedAt = value.Time
			}
		case department.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				d.UpdatedAt = value.Time
			}
		case department.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_departments", value)
			} else if value.Valid {
				d.user_departments = new(int)
				*d.user_departments = int(value.Int64)
			}
		default:
			d.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Department.
// This includes values selected through modifiers, order, etc.
func (d *Department) Value(name string) (ent.Value, error) {
	return d.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Department entity.
func (d *Department) QueryOwner() *UserQuery {
	return NewDepartmentClient(d.config).QueryOwner(d)
}

// QueryMembers queries the "members" edge of the Department entity.
func (d *Department) QueryMembers() *MemberQuery {
	return NewDepartmentClient(d.config).QueryMembers(d)
}

// QueryAPIKeys queries the "api_keys" edge of the Department entity.
func (d *Department) QueryAPIKeys() *APIKeyQuery {
	return NewDepartmentClient(d.config).QueryAPIKeys(d)
}

// Update returns a builder for updating this Department.
// Note that you need to call Department.Unwrap() before calling this method if this Department
// was returned from a transaction, and the transaction was committed or rolled back.
func (d *Department) Update() *DepartmentUpdateOne {
	return NewDepartmentClient(d.config).UpdateOne(d)
}

// Unwrap unwraps the Department entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (d *Department) Unwrap() *Department {
	_tx, ok := d.config.driver.(*txDriver)
	if !ok {
		panic("ent: Department is not a transactional entity")
	}
	d.config.driver = _tx.drv
	return d
}

// String implements the fmt.Stringer.
func (d *Department) String() string {
	var builder strings.Builder
	builder.WriteString("Department(")
	builder.WriteString(fmt.Sprintf("id=%v, ", d.ID))
	builder.WriteString("name=")
	builder.WriteString(d.Name)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(d.Note)
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", d.Sort))
	builder.WriteString(", ")
	builder.WriteString("quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", d.QuotaUsd))
	builder.WriteString(", ")
	builder.WriteString("quota_period=")
	builder.WriteString(fmt.Sprintf("%v", d.QuotaPeriod))
	builder.WriteString(", ")
	builder.WriteString("period_anchor=")
	builder.WriteString(d.PeriodAnchor.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("period_start=")
	builder.WriteString(d.PeriodStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("period_used_base=")
	builder.WriteString(fmt.Sprintf("%v", d.PeriodUsedBase))
	builder.WriteString(", ")
	builder.WriteString("used_quota=")
	builder.WriteString(fmt.Sprintf("%v", d.UsedQuota))
	builder.WriteString(", ")
	builder.WriteString("used_quota_actual=")
	builder.WriteString(fmt.Sprintf("%v", d.UsedQuotaActual))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(d.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(d.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Departments is a parsable slice of Department.
type Departments []*Department
