// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/referralcommission"
)

// ReferralCommission is the model entity for the ReferralCommission schema.
type ReferralCommission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 推广官 user id 快照（kind=rebate 的受益人）。
	InviterID int `json:"inviter_id,omitempty"`
	// 推广官邮箱快照。
	InviterEmail string `json:"inviter_email,omitempty"`
	// 被邀请人 user id 快照（kind=first_bonus 的受益人）。
	InviteeID int `json:"invitee_id,omitempty"`
	// 被邀请人邮箱快照。
	InviteeEmail string `json:"invitee_email,omitempty"`
	// 关联充值订单号（支付插件侧）。
	OutTradeNo string `json:"out_trade_no,omitempty"`
	// rebate=推广官返利；first_bonus=被邀请人首充加赠。
	Kind referralcommission.Kind `json:"kind,omitempty"`
	// 订单实付金额（计算基数，不含套餐赠送）。
	PaidAmount float64 `json:"paid_amount,omitempty"`
	// 入账时生效的比例快照，防事后调比例对不上账。
	Rate float64 `json:"rate,omitempty"`
	// 实际入账金额 = paid_amount × rate。
	Amount float64 `json:"amount,omitempty"`
	// settled=已入账；reversed=已回冲（退款/作弊人工处理）。预留结算态扩展。
	Status referralcommission.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 回冲时间；NULL 表示未回冲。
	ReversedAt   *time.Time `json:"reversed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralCommission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldPaidAmount, referralcommission.FieldRate, referralcommission.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case referralcommission.FieldID, referralcommission.FieldInviterID, referralcommission.FieldInviteeID:
			values[i] = new(sql.NullInt64)
		case referralcommission.FieldInviterEmail, referralcommission.FieldInviteeEmail, referralcommission.FieldOutTradeNo, referralcommission.FieldKind, referralcommission.FieldStatus:
			values[i] = new(sql.NullString)
		case referralcommission.FieldCreatedAt, referralcommission.FieldReversedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralCommission fields.
func (rc *ReferralCommission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rc.ID = int(value.Int64)
		case referralcommission.FieldInviterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value.Valid {
				rc.InviterID = int(value.Int64)
			}
		case referralcommission.FieldInviterEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_email", values[i])
			} else if value.Valid {
				rc.InviterEmail = value.String
			}
		case referralcommission.FieldInviteeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_id", values[i])
			} else if value.Valid {
				rc.InviteeID = int(value.Int64)
			}
		case referralcommission.FieldInviteeEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_email", values[i])
			} else if value.Valid {
				rc.InviteeEmail = value.String
			}
		case referralcommission.FieldOutTradeNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field out_trade_no", values[i])
			} else if value.Valid {
				rc.OutTradeNo = value.String
			}
		case referralcommission.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				rc.Kind = referralcommission.Kind(value.String)
			}
		case referralcommission.FieldPaidAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field paid_amount", values[i])
			} else if value.Valid {
				rc.PaidAmount = value.Float64
			}
		case referralcommission.FieldRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate", values[i])
			} else if value.Valid {
				rc.Rate = value.Float64
			}
		case referralcommission.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				rc.Amount = value.Float64
			}
		case referralcommission.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				rc.Status = referralcommission.Status(value.String)
			}
		case referralcommission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				rc.CreatedAt = value.Time
			}
		case referralcommission.FieldReversedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reversed_at", values[i])
			} else if value.Valid {
				rc.ReversedAt = new(time.Time)
				*rc.ReversedAt = value.Time
			}
		default:
			rc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralCommission.
// This includes values selected through modifiers, order, etc.
func (rc *ReferralCommission) Value(name string) (ent.Value, error) {
	return rc.selectValues.Get(name)
}

// Update returns a builder for updating this ReferralCommission.
// Note that you need to call ReferralCommission.Unwrap() before calling this method if this ReferralCommission
// was returned from a transaction, and the transaction was committed or rolled back.
func (rc *ReferralCommission) Update() *ReferralCommissionUpdateOne {
	return NewReferralCommissionClient(rc.config).UpdateOne(rc)
}

// Unwrap unwraps the ReferralCommission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rc *ReferralCommission) Unwrap() *ReferralCommission {
	_tx, ok := rc.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralCommission is not a transactional entity")
	}
	rc.config.driver = _tx.drv
	return rc
}

// String implements the fmt.Stringer.
func (rc *ReferralCommission) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralCommission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rc.ID))
	builder.WriteString("inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", rc.InviterID))
	builder.WriteString(", ")
	builder.WriteString("inviter_email=")
	builder.WriteString(rc.InviterEmail)
	builder.WriteString(", ")
	builder.WriteString("invitee_id=")
	builder.WriteString(fmt.Sprintf("%v", rc.InviteeID))
	builder.WriteString(", ")
	builder.WriteString("invitee_email=")
	builder.WriteString(rc.InviteeEmail)
	builder.WriteString(", ")
	builder.WriteString("out_trade_no=")
	builder.WriteString(rc.OutTradeNo)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", rc.Kind))
	builder.WriteString(", ")
	builder.WriteString("paid_amount=")
	builder.WriteString(fmt.Sprintf("%v", rc.PaidAmount))
	builder.WriteString(", ")
	builder.WriteString("rate=")
	builder.WriteString(fmt.Sprintf("%v", rc.Rate))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", rc.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", rc.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(rc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := rc.ReversedAt; v != nil {
		builder.WriteString("reversed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ReferralCommissions is a parsable slice of ReferralCommission.
type ReferralCommissions []*ReferralCommission
