// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
	"github.com/DouDOU-start/airgate-core/ent/referralcommission"
)

// ReferralCommissionQuery is the builder for querying ReferralCommission entities.
type ReferralCommissionQuery struct {
	config
	ctx        *QueryContext
	order      []referralcommission.OrderOption
	inters     []Interceptor
	predicates []predicate.ReferralCommission
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReferralCommissionQuery builder.
func (rcq *ReferralCommissionQuery) Where(ps ...predicate.ReferralCommission) *ReferralCommissionQuery {
	rcq.predicates = append(rcq.predicates, ps...)
	return rcq
}

// Limit the number of records to be returned by this query.
func (rcq *ReferralCommissionQuery) Limit(limit int) *ReferralCommissionQuery {
	rcq.ctx.Limit = &limit
	return rcq
}

// Offset to start from.
func (rcq *ReferralCommissionQuery) Offset(offset int) *ReferralCommissionQuery {
	rcq.ctx.Offset = &offset
	return rcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rcq *ReferralCommissionQuery) Unique(unique bool) *ReferralCommissionQuery {
	rcq.ctx.Unique = &unique
	return rcq
}

// Order specifies how the records should be ordered.
func (rcq *ReferralCommissionQuery) Order(o ...referralcommission.OrderOption) *ReferralCommissionQuery {
	rcq.order = append(rcq.order, o...)
	return rcq
}

// First returns the first ReferralCommission entity from the query.
// Returns a *NotFoundError when no ReferralCommission was found.
func (rcq *ReferralCommissionQuery) First(ctx context.Context) (*ReferralCommission, error) {
	nodes, err := rcq.Limit(1).All(setContextOp(ctx, rcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{referralcommission.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) FirstX(ctx context.Context) *ReferralCommission {
	node, err := rcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ReferralCommission ID from the query.
// Returns a *NotFoundError when no ReferralCommission ID was found.
func (rcq *ReferralCommissionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(1).IDs(setContextOp(ctx, rcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{referralcommission.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) FirstIDX(ctx context.Context) int {
	id, err := rcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ReferralCommission entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ReferralCommission entity is found.
// Returns a *NotFoundError when no ReferralCommission entities are found.
func (rcq *ReferralCommissionQuery) Only(ctx context.Context) (*ReferralCommission, error) {
	nodes, err := rcq.Limit(2).All(setContextOp(ctx, rcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{referralcommission.Label}
	default:
		return nil, &NotSingularError{referralcommission.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) OnlyX(ctx context.Context) *ReferralCommission {
	node, err := rcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ReferralCommission ID in the query.
// Returns a *NotSingularError when more than one ReferralCommission ID is found.
// Returns a *NotFoundError when no entities are found.
func (rcq *ReferralCommissionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rcq.Limit(2).IDs(setContextOp(ctx, rcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{referralcommission.Label}
	default:
		err = &NotSingularError{referralcommission.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) OnlyIDX(ctx context.Context) int {
	id, err := rcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ReferralCommissions.
func (rcq *ReferralCommissionQuery) All(ctx context.Context) ([]*ReferralCommission, error) {
	ctx = setContextOp(ctx, rcq.ctx, "All")
	if err := rcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ReferralCommission, *ReferralCommissionQuery]()
	return withInterceptors[[]*ReferralCommission](ctx, rcq, qr, rcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) AllX(ctx context.Context) []*ReferralCommission {
	nodes, err := rcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ReferralCommission IDs.
func (rcq *ReferralCommissionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rcq.ctx.Unique == nil && rcq.path != nil {
		rcq.Unique(true)
	}
	ctx = setContextOp(ctx, rcq.ctx, "IDs")
	if err = rcq.Select(referralcommission.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) IDsX(ctx context.Context) []int {
	ids, err := rcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rcq *ReferralCommissionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rcq.ctx, "Count")
	if err := rcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rcq, querierCount[*ReferralCommissionQuery](), rcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) CountX(ctx context.Context) int {
	count, err := rcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rcq *ReferralCommissionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rcq.ctx, "Exist")
	switch _, err := rcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rcq *ReferralCommissionQuery) ExistX(ctx context.Context) bool {
	exist, err := rcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReferralCommissionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rcq *ReferralCommissionQuery) Clone() *ReferralCommissionQuery {
	if rcq == nil {
		return nil
	}
	return &ReferralCommissionQuery{
		config:     rcq.config,
		ctx:        rcq.ctx.Clone(),
		order:      append([]referralcommission.OrderOption{}, rcq.order...),
		inters:     append([]Interceptor{}, rcq.inters...),
		predicates: append([]predicate.ReferralCommission{}, rcq.predicates...),
		// clone intermediate query.
		sql:  rcq.sql.Clone(),
		path: rcq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		InviterID int `json:"inviter_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ReferralCommission.Query().
//		GroupBy(referralcommission.FieldInviterID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rcq *ReferralCommissionQuery) GroupBy(field string, fields ...string) *ReferralCommissionGroupBy {
	rcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReferralCommissionGroupBy{build: rcq}
	grbuild.flds = &rcq.ctx.Fields
	grbuild.label = referralcommission.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		InviterID int `json:"inviter_id,omitempty"`
//	}
//
//	client.ReferralCommission.Query().
//		Select(referralcommission.FieldInviterID).
//		Scan(ctx, &v)
func (rcq *ReferralCommissionQuery) Select(fields ...string) *ReferralCommissionSelect {
	rcq.ctx.Fields = append(rcq.ctx.Fields, fields...)
	sbuild := &ReferralCommissionSelect{ReferralCommissionQuery: rcq}
	sbuild.label = referralcommission.Label
	sbuild.flds, sbuild.scan = &rcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReferralCommissionSelect configured with the given aggregations.
func (rcq *ReferralCommissionQuery) Aggregate(fns ...AggregateFunc) *ReferralCommissionSelect {
	return rcq.Select().Aggregate(fns...)
}

func (rcq *ReferralCommissionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rcq); err != nil {
				return err
			}
		}
	}
	for _, f := range rcq.ctx.Fields {
		if !referralcommission.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rcq.path != nil {
		prev, err := rcq.path(ctx)
		if err != nil {
			return err
		}
		rcq.sql = prev
	}
	return nil
}

func (rcq *ReferralCommissionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ReferralCommission, error) {
	var (
		nodes = []*ReferralCommission{}
		_spec = rcq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ReferralCommission).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ReferralCommission{config: rcq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rcq *ReferralCommissionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rcq.querySpec()
	_spec.Node.Columns = rcq.ctx.Fields
	if len(rcq.ctx.Fields) > 0 {
		_spec.Unique = rcq.ctx.Unique != nil && *rcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rcq.driver, _spec)
}

func (rcq *ReferralCommissionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt))
	_spec.From = rcq.sql
	if unique := rcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rcq.path != nil {
		_spec.Unique = true
	}
	if fields := rcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommission.FieldID)
		for i := range fields {
			if fields[i] != referralcommission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rcq *ReferralCommissionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rcq.driver.Dialect())
	t1 := builder.Table(referralcommission.Table)
	columns := rcq.ctx.Fields
	if len(columns) == 0 {
		columns = referralcommission.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rcq.sql != nil {
		selector = rcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rcq.ctx.Unique != nil && *rcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rcq.predicates {
		p(selector)
	}
	for _, p := range rcq.order {
		p(selector)
	}
	if offset := rcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReferralCommissionGroupBy is the group-by builder for ReferralCommission entities.
type ReferralCommissionGroupBy struct {
	selector
	build *ReferralCommissionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rcgb *ReferralCommissionGroupBy) Aggregate(fns ...AggregateFunc) *ReferralCommissionGroupBy {
	rcgb.fns = append(rcgb.fns, fns...)
	return rcgb
}

// Scan applies the selector query and scans the result into the given value.
func (rcgb *ReferralCommissionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcgb.build.ctx, "GroupBy")
	if err := rcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReferralCommissionQuery, *ReferralCommissionGroupBy](ctx, rcgb.build, rcgb, rcgb.build.inters, v)
}

func (rcgb *ReferralCommissionGroupBy) sqlScan(ctx context.Context, root *ReferralCommissionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rcgb.fns))
	for _, fn := range rcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rcgb.flds)+len(rcgb.fns))
		for _, f := range *rcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReferralCommissionSelect is the builder for selecting fields of ReferralCommission entities.
type ReferralCommissionSelect struct {
	*ReferralCommissionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rcs *ReferralCommissionSelect) Aggregate(fns ...AggregateFunc) *ReferralCommissionSelect {
	rcs.fns = append(rcs.fns, fns...)
	return rcs
}

// Scan applies the selector query and scans the result into the given value.
func (rcs *ReferralCommissionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rcs.ctx, "Select")
	if err := rcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReferralCommissionQuery, *ReferralCommissionSelect](ctx, rcs.ReferralCommissionQuery, rcs, rcs.inters, v)
}

func (rcs *ReferralCommissionSelect) sqlScan(ctx context.Context, root *ReferralCommissionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rcs.fns))
	for _, fn := range rcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
