// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/referralcommission"
)

// ReferralCommissionCreate is the builder for creating a ReferralCommission entity.
type ReferralCommissionCreate struct {
	config
	mutation *ReferralCommissionMutation
	hooks    []Hook
}

// SetInviterID sets the "inviter_id" field.
func (rcc *ReferralCommissionCreate) SetInviterID(i int) *ReferralCommissionCreate {
	rcc.mutation.SetInviterID(i)
	return rcc
}

// SetInviterEmail sets the "inviter_email" field.
func (rcc *ReferralCommissionCreate) SetInviterEmail(s string) *ReferralCommissionCreate {
	rcc.mutation.SetInviterEmail(s)
	return rcc
}

// SetNillableInviterEmail sets the "inviter_email" field if the given value is not nil.
func (rcc *ReferralCommissionCreate) SetNillableInviterEmail(s *string) *ReferralCommissionCreate {
	if s != nil {
		rcc.SetInviterEmail(*s)
	}
	return rcc
}

// SetInviteeID sets the "invitee_id" field.
func (rcc *ReferralCommissionCreate) SetInviteeID(i int) *ReferralCommissionCreate {
	rcc.mutation.SetInviteeID(i)
	return rcc
}

// SetInviteeEmail sets the "invitee_email" field.
func (rcc *ReferralCommissionCreate) SetInviteeEmail(s string) *ReferralCommissionCreate {
	rcc.mutation.SetInviteeEmail(s)
	return rcc
}

// SetNillableInviteeEmail sets the "invitee_email" field if the given value is not nil.
func (rcc *ReferralCommissionCreate) SetNillableInviteeEmail(s *string) *ReferralCommissionCreate {
	if s != nil {
		rcc.SetInviteeEmail(*s)
	}
	return rcc
}

// SetOutTradeNo sets the "out_trade_no" field.
func (rcc *ReferralCommissionCreate) SetOutTradeNo(s string) *ReferralCommissionCreate {
	rcc.mutation.SetOutTradeNo(s)
	return rcc
}

// SetKind sets the "kind" field.
func (rcc *ReferralCommissionCreate) SetKind(r referralcommission.Kind) *ReferralCommissionCreate {
	rcc.mutation.SetKind(r)
	return rcc
}

// SetPaidAmount sets the "paid_amount" field.
func (rcc *ReferralCommissionCreate) SetPaidAmount(f float64) *ReferralCommissionCreate {
	rcc.mutation.SetPaidAmount(f)
	return rcc
}

// SetRate sets the "rate" field.
func (rcc *ReferralCommissionCreate) SetRate(f float64) *ReferralCommissionCreate {
	rcc.mutation.SetRate(f)
	return rcc
}

// SetAmount sets the "amount" field.
func (rcc *ReferralCommissionCreate) SetAmount(f float64) *ReferralCommissionCreate {
	rcc.mutation.SetAmount(f)
	return rcc
}

// SetStatus sets the "status" field.
func (rcc *ReferralCommissionCreate) SetStatus(r referralcommission.Status) *ReferralCommissionCreate {
	rcc.mutation.SetStatus(r)
	return rcc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rcc *ReferralCommissionCreate) SetNillableStatus(r *referralcommission.Status) *ReferralCommissionCreate {
	if r != nil {
		rcc.SetStatus(*r)
	}
	return rcc
}

// SetCreatedAt sets the "created_at" field.
func (rcc *ReferralCommissionCreate) SetCreatedAt(t time.Time) *ReferralCommissionCreate {
	rcc.mutation.SetCreatedAt(t)
	return rcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rcc *ReferralCommissionCreate) SetNillableCreatedAt(t *time.Time) *ReferralCommissionCreate {
	if t != nil {
		rcc.SetCreatedAt(*t)
	}
	return rcc
}

// SetReversedAt sets the "reversed_at" field.
func (rcc *ReferralCommissionCreate) SetReversedAt(t time.Time) *ReferralCommissionCreate {
	rcc.mutation.SetReversedAt(t)
	return rcc
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (rcc *ReferralCommissionCreate) SetNillableReversedAt(t *time.Time) *ReferralCommissionCreate {
	if t != nil {
		rcc.SetReversedAt(*t)
	}
	return rcc
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (rcc *ReferralCommissionCreate) Mutation() *ReferralCommissionMutation {
	return rcc.mutation
}

// Save creates the ReferralCommission in the database.
func (rcc *ReferralCommissionCreate) Save(ctx context.Context) (*ReferralCommission, error) {
	rcc.defaults()
	return withHooks(ctx, rcc.sqlSave, rcc.mutation, rcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rcc *ReferralCommissionCreate) SaveX(ctx context.Context) *ReferralCommission {
	v, err := rcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcc *ReferralCommissionCreate) Exec(ctx context.Context) error {
	_, err := rcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcc *ReferralCommissionCreate) ExecX(ctx context.Context) {
	if err := rcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rcc *ReferralCommissionCreate) defaults() {
	if _, ok := rcc.mutation.InviterEmail(); !ok {
		v := referralcommission.DefaultInviterEmail
		rcc.mutation.SetInviterEmail(v)
	}
	if _, ok := rcc.mutation.InviteeEmail(); !ok {
		v := referralcommission.DefaultInviteeEmail
		rcc.mutation.SetInviteeEmail(v)
	}
	if _, ok := rcc.mutation.Status(); !ok {
		v := referralcommission.DefaultStatus
		rcc.mutation.SetStatus(v)
	}
	if _, ok := rcc.mutation.CreatedAt(); !ok {
		v := referralcommission.DefaultCreatedAt()
		rcc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rcc *ReferralCommissionCreate) check() error {
	if _, ok := rcc.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "ReferralCommission.inviter_id"`)}
	}
	if _, ok := rcc.mutation.InviterEmail(); !ok {
		return &ValidationError{Name: "inviter_email", err: errors.New(`ent: missing required field "ReferralCommission.inviter_email"`)}
	}
	if _, ok := rcc.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "ReferralCommission.invitee_id"`)}
	}
	if _, ok := rcc.mutation.InviteeEmail(); !ok {
		return &ValidationError{Name: "invitee_email", err: errors.New(`ent: missing required field "ReferralCommission.invitee_email"`)}
	}
	if _, ok := rcc.mutation.OutTradeNo(); !ok {
		return &ValidationError{Name: "out_trade_no", err: errors.New(`ent: missing required field "ReferralCommission.out_trade_no"`)}
	}
	if v, ok := rcc.mutation.OutTradeNo(); ok {
		if err := referralcommission.OutTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "out_trade_no", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.out_trade_no": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ReferralCommission.kind"`)}
	}
	if v, ok := rcc.mutation.Kind(); ok {
		if err := referralcommission.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.kind": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.PaidAmount(); !ok {
		return &ValidationError{Name: "paid_amount", err: errors.New(`ent: missing required field "ReferralCommission.paid_amount"`)}
	}
	if _, ok := rcc.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "ReferralCommission.rate"`)}
	}
	if _, ok := rcc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "ReferralCommission.amount"`)}
	}
	if _, ok := rcc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReferralCommission.status"`)}
	}
	if v, ok := rcc.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	if _, ok := rcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralCommission.created_at"`)}
	}
	return nil
}

func (rcc *ReferralCommissionCreate) sqlSave(ctx context.Context) (*ReferralCommission, error) {
	if err := rcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rcc.mutation.id = &_node.ID
	rcc.mutation.done = true
	return _node, nil
}

func (rcc *ReferralCommissionCreate) createSpec() (*ReferralCommission, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralCommission{config: rcc.config}
		_spec = sqlgraph.NewCreateSpec(referralcommission.Table, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt))
	)
	if value, ok := rcc.mutation.InviterID(); ok {
		_spec.SetField(referralcommission.FieldInviterID, field.TypeInt, value)
		_node.InviterID = value
	}
	if value, ok := rcc.mutation.InviterEmail(); ok {
		_spec.SetField(referralcommission.FieldInviterEmail, field.TypeString, value)
		_node.InviterEmail = value
	}
	if value, ok := rcc.mutation.InviteeID(); ok {
		_spec.SetField(referralcommission.FieldInviteeID, field.TypeInt, value)
		_node.InviteeID = value
	}
	if value, ok := rcc.mutation.InviteeEmail(); ok {
		_spec.SetField(referralcommission.FieldInviteeEmail, field.TypeString, value)
		_node.InviteeEmail = value
	}
	if value, ok := rcc.mutation.OutTradeNo(); ok {
		_spec.SetField(referralcommission.FieldOutTradeNo, field.TypeString, value)
		_node.OutTradeNo = value
	}
	if value, ok := rcc.mutation.Kind(); ok {
		_spec.SetField(referralcommission.FieldKind, field.TypeEnum, value)
		_node.Kind = value
	}
	if value, ok := rcc.mutation.PaidAmount(); ok {
		_spec.SetField(referralcommission.FieldPaidAmount, field.TypeFloat64, value)
		_node.PaidAmount = value
	}
	if value, ok := rcc.mutation.Rate(); ok {
		_spec.SetField(referralcommission.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := rcc.mutation.Amount(); ok {
		_spec.SetField(referralcommission.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := rcc.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := rcc.mutation.CreatedAt(); ok {
		_spec.SetField(referralcommission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rcc.mutation.ReversedAt(); ok {
		_spec.SetField(referralcommission.FieldReversedAt, field.TypeTime, value)
		_node.ReversedAt = &value
	}
	return _node, _spec
}

// ReferralCommissionCreateBulk is the builder for creating many ReferralCommission entities in bulk.
type ReferralCommissionCreateBulk struct {
	config
	err      error
	builders []*ReferralCommissionCreate
}

// Save creates the ReferralCommission entities in the database.
func (rccb *ReferralCommissionCreateBulk) Save(ctx context.Context) ([]*ReferralCommission, error) {
	if rccb.err != nil {
		return nil, rccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rccb.builders))
	nodes := make([]*ReferralCommission, len(rccb.builders))
	mutators := make([]Mutator, len(rccb.builders))
	for i := range rccb.builders {
		func(i int, root context.Context) {
			builder := rccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralCommissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rccb *ReferralCommissionCreateBulk) SaveX(ctx context.Context) []*ReferralCommission {
	v, err := rccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rccb *ReferralCommissionCreateBulk) Exec(ctx context.Context) error {
	_, err := rccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rccb *ReferralCommissionCreateBulk) ExecX(ctx context.Context) {
	if err := rccb.Exec(ctx); err != nil {
		panic(err)
	}
}
