// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
	"github.com/DouDOU-start/airgate-core/ent/subscriptionreservation"
)

// SubscriptionReservationDelete is the builder for deleting a SubscriptionReservation entity.
type SubscriptionReservationDelete struct {
	config
	hooks    []Hook
	mutation *SubscriptionReservationMutation
}

// Where appends a list predicates to the SubscriptionReservationDelete builder.
func (srd *SubscriptionReservationDelete) Where(ps ...predicate.SubscriptionReservation) *SubscriptionReservationDelete {
	srd.mutation.Where(ps...)
	return srd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (srd *SubscriptionReservationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, srd.sqlExec, srd.mutation, srd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (srd *SubscriptionReservationDelete) ExecX(ctx context.Context) int {
	n, err := srd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (srd *SubscriptionReservationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(subscriptionreservation.Table, sqlgraph.NewFieldSpec(subscriptionreservation.FieldID, field.TypeInt))
	if ps := srd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, srd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	srd.mutation.done = true
	return affected, err
}

// SubscriptionReservationDeleteOne is the builder for deleting a single SubscriptionReservation entity.
type SubscriptionReservationDeleteOne struct {
	srd *SubscriptionReservationDelete
}

// Where appends a list predicates to the SubscriptionReservationDelete builder.
func (srdo *SubscriptionReservationDeleteOne) Where(ps ...predicate.SubscriptionReservation) *SubscriptionReservationDeleteOne {
	srdo.srd.mutation.Where(ps...)
	return srdo
}

// Exec executes the deletion query.
func (srdo *SubscriptionReservationDeleteOne) Exec(ctx context.Context) error {
	n, err := srdo.srd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{subscriptionreservation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (srdo *SubscriptionReservationDeleteOne) ExecX(ctx context.Context) {
	if err := srdo.Exec(ctx); err != nil {
		panic(err)
	}
}
