// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
	"github.com/DouDOU-start/airgate-core/ent/teamauditlog"
)

// TeamAuditLogUpdate is the builder for updating TeamAuditLog entities.
type TeamAuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *TeamAuditLogMutation
}

// Where appends a list predicates to the TeamAuditLogUpdate builder.
func (talu *TeamAuditLogUpdate) Where(ps ...predicate.TeamAuditLog) *TeamAuditLogUpdate {
	talu.mutation.Where(ps...)
	return talu
}

// SetOwnerID sets the "owner_id" field.
func (talu *TeamAuditLogUpdate) SetOwnerID(i int) *TeamAuditLogUpdate {
	talu.mutation.ResetOwnerID()
	talu.mutation.SetOwnerID(i)
	return talu
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableOwnerID(i *int) *TeamAuditLogUpdate {
	if i != nil {
		talu.SetOwnerID(*i)
	}
	return talu
}

// AddOwnerID adds i to the "owner_id" field.
func (talu *TeamAuditLogUpdate) AddOwnerID(i int) *TeamAuditLogUpdate {
	talu.mutation.AddOwnerID(i)
	return talu
}

// SetActorUserID sets the "actor_user_id" field.
func (talu *TeamAuditLogUpdate) SetActorUserID(i int) *TeamAuditLogUpdate {
	talu.mutation.ResetActorUserID()
	talu.mutation.SetActorUserID(i)
	return talu
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableActorUserID(i *int) *TeamAuditLogUpdate {
	if i != nil {
		talu.SetActorUserID(*i)
	}
	return talu
}

// AddActorUserID adds i to the "actor_user_id" field.
func (talu *TeamAuditLogUpdate) AddActorUserID(i int) *TeamAuditLogUpdate {
	talu.mutation.AddActorUserID(i)
	return talu
}

// SetActorEmail sets the "actor_email" field.
func (talu *TeamAuditLogUpdate) SetActorEmail(s string) *TeamAuditLogUpdate {
	talu.mutation.SetActorEmail(s)
	return talu
}

// SetNillableActorEmail sets the "actor_email" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableActorEmail(s *string) *TeamAuditLogUpdate {
	if s != nil {
		talu.SetActorEmail(*s)
	}
	return talu
}

// SetAction sets the "action" field.
func (talu *TeamAuditLogUpdate) SetAction(s string) *TeamAuditLogUpdate {
	talu.mutation.SetAction(s)
	return talu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableAction(s *string) *TeamAuditLogUpdate {
	if s != nil {
		talu.SetAction(*s)
	}
	return talu
}

// SetTargetType sets the "target_type" field.
func (talu *TeamAuditLogUpdate) SetTargetType(s string) *TeamAuditLogUpdate {
	talu.mutation.SetTargetType(s)
	return talu
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableTargetType(s *string) *TeamAuditLogUpdate {
	if s != nil {
		talu.SetTargetType(*s)
	}
	return talu
}

// SetTargetID sets the "target_id" field.
func (talu *TeamAuditLogUpdate) SetTargetID(i int) *TeamAuditLogUpdate {
	talu.mutation.ResetTargetID()
	talu.mutation.SetTargetID(i)
	return talu
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableTargetID(i *int) *TeamAuditLogUpdate {
	if i != nil {
		talu.SetTargetID(*i)
	}
	return talu
}

// AddTargetID adds i to the "target_id" field.
func (talu *TeamAuditLogUpdate) AddTargetID(i int) *TeamAuditLogUpdate {
	talu.mutation.AddTargetID(i)
	return talu
}

// SetTargetName sets the "target_name" field.
func (talu *TeamAuditLogUpdate) SetTargetName(s string) *TeamAuditLogUpdate {
	talu.mutation.SetTargetName(s)
	return talu
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableTargetName(s *string) *TeamAuditLogUpdate {
	if s != nil {
		talu.SetTargetName(*s)
	}
	return talu
}

// SetBefore sets the "before" field.
func (talu *TeamAuditLogUpdate) SetBefore(m map[string]interface{}) *TeamAuditLogUpdate {
	talu.mutation.SetBefore(m)
	return talu
}

// ClearBefore clears the value of the "before" field.
func (talu *TeamAuditLogUpdate) ClearBefore() *TeamAuditLogUpdate {
	talu.mutation.ClearBefore()
	return talu
}

// SetAfter sets the "after" field.
func (talu *TeamAuditLogUpdate) SetAfter(m map[string]interface{}) *TeamAuditLogUpdate {
	talu.mutation.SetAfter(m)
	return talu
}

// ClearAfter clears the value of the "after" field.
func (talu *TeamAuditLogUpdate) ClearAfter() *TeamAuditLogUpdate {
	talu.mutation.ClearAfter()
	return talu
}

// SetIP sets the "ip" field.
func (talu *TeamAuditLogUpdate) SetIP(s string) *TeamAuditLogUpdate {
	talu.mutation.SetIP(s)
	return talu
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableIP(s *string) *TeamAuditLogUpdate {
	if s != nil {
		talu.SetIP(*s)
	}
	return talu
}

// SetRequestID sets the "request_id" field.
func (talu *TeamAuditLogUpdate) SetRequestID(s string) *TeamAuditLogUpdate {
	talu.mutation.SetRequestID(s)
	return talu
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (talu *TeamAuditLogUpdate) SetNillableRequestID(s *string) *TeamAuditLogUpdate {
	if s != nil {
		talu.SetRequestID(*s)
	}
	return talu
}

// Mutation returns the TeamAuditLogMutation object of the builder.
func (talu *TeamAuditLogUpdate) Mutation() *TeamAuditLogMutation {
	return talu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (talu *TeamAuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, talu.sqlSave, talu.mutation, talu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (talu *TeamAuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := talu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (talu *TeamAuditLogUpdate) Exec(ctx context.Context) error {
	_, err := talu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (talu *TeamAuditLogUpdate) ExecX(ctx context.Context) {
	if err := talu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (talu *TeamAuditLogUpdate) check() error {
	if v, ok := talu.mutation.ActorEmail(); ok {
		if err := teamauditlog.ActorEmailValidator(v); err != nil {
			return &ValidationError{Name: "actor_email", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.actor_email": %w`, err)}
		}
	}
	if v, ok := talu.mutation.Action(); ok {
		if err := teamauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.action": %w`, err)}
		}
	}
	if v, ok := talu.mutation.TargetType(); ok {
		if err := teamauditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := talu.mutation.TargetName(); ok {
		if err := teamauditlog.TargetNameValidator(v); err != nil {
			return &ValidationError{Name: "target_name", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.target_name": %w`, err)}
		}
	}
	if v, ok := talu.mutation.IP(); ok {
		if err := teamauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.ip": %w`, err)}
		}
	}
	if v, ok := talu.mutation.RequestID(); ok {
		if err := teamauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.request_id": %w`, err)}
		}
	}
	return nil
}

func (talu *TeamAuditLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := talu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamauditlog.Table, teamauditlog.Columns, sqlgraph.NewFieldSpec(teamauditlog.FieldID, field.TypeInt))
	if ps := talu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := talu.mutation.OwnerID(); ok {
		_spec.SetField(teamauditlog.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := talu.mutation.AddedOwnerID(); ok {
		_spec.AddField(teamauditlog.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := talu.mutation.ActorUserID(); ok {
		_spec.SetField(teamauditlog.FieldActorUserID, field.TypeInt, value)
	}
	if value, ok := talu.mutation.AddedActorUserID(); ok {
		_spec.AddField(teamauditlog.FieldActorUserID, field.TypeInt, value)
	}
	if value, ok := talu.mutation.ActorEmail(); ok {
		_spec.SetField(teamauditlog.FieldActorEmail, field.TypeString, value)
	}
	if value, ok := talu.mutation.Action(); ok {
		_spec.SetField(teamauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := talu.mutation.TargetType(); ok {
		_spec.SetField(teamauditlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := talu.mutation.TargetID(); ok {
		_spec.SetField(teamauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := talu.mutation.AddedTargetID(); ok {
		_spec.AddField(teamauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := talu.mutation.TargetName(); ok {
		_spec.SetField(teamauditlog.FieldTargetName, field.TypeString, value)
	}
	if value, ok := talu.mutation.Before(); ok {
		_spec.SetField(teamauditlog.FieldBefore, field.TypeJSON, value)
	}
	if talu.mutation.BeforeCleared() {
		_spec.ClearField(teamauditlog.FieldBefore, field.TypeJSON)
	}
	if value, ok := talu.mutation.After(); ok {
		_spec.SetField(teamauditlog.FieldAfter, field.TypeJSON, value)
	}
	if talu.mutation.AfterCleared() {
		_spec.ClearField(teamauditlog.FieldAfter, field.TypeJSON)
	}
	if value, ok := talu.mutation.IP(); ok {
		_spec.SetField(teamauditlog.FieldIP, field.TypeString, value)
	}
	if value, ok := talu.mutation.RequestID(); ok {
		_spec.SetField(teamauditlog.FieldRequestID, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, talu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	talu.mutation.done = true
	return n, nil
}

// TeamAuditLogUpdateOne is the builder for updating a single TeamAuditLog entity.
type TeamAuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamAuditLogMutation
}

// SetOwnerID sets the "owner_id" field.
func (taluo *TeamAuditLogUpdateOne) SetOwnerID(i int) *TeamAuditLogUpdateOne {
	taluo.mutation.ResetOwnerID()
	taluo.mutation.SetOwnerID(i)
	return taluo
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableOwnerID(i *int) *TeamAuditLogUpdateOne {
	if i != nil {
		taluo.SetOwnerID(*i)
	}
	return taluo
}

// AddOwnerID adds i to the "owner_id" field.
func (taluo *TeamAuditLogUpdateOne) AddOwnerID(i int) *TeamAuditLogUpdateOne {
	taluo.mutation.AddOwnerID(i)
	return taluo
}

// SetActorUserID sets the "actor_user_id" field.
func (taluo *TeamAuditLogUpdateOne) SetActorUserID(i int) *TeamAuditLogUpdateOne {
	taluo.mutation.ResetActorUserID()
	taluo.mutation.SetActorUserID(i)
	return taluo
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableActorUserID(i *int) *TeamAuditLogUpdateOne {
	if i != nil {
		taluo.SetActorUserID(*i)
	}
	return taluo
}

// AddActorUserID adds i to the "actor_user_id" field.
func (taluo *TeamAuditLogUpdateOne) AddActorUserID(i int) *TeamAuditLogUpdateOne {
	taluo.mutation.AddActorUserID(i)
	return taluo
}

// SetActorEmail sets the "actor_email" field.
func (taluo *TeamAuditLogUpdateOne) SetActorEmail(s string) *TeamAuditLogUpdateOne {
	taluo.mutation.SetActorEmail(s)
	return taluo
}

// SetNillableActorEmail sets the "actor_email" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableActorEmail(s *string) *TeamAuditLogUpdateOne {
	if s != nil {
		taluo.SetActorEmail(*s)
	}
	return taluo
}

// SetAction sets the "action" field.
func (taluo *TeamAuditLogUpdateOne) SetAction(s string) *TeamAuditLogUpdateOne {
	taluo.mutation.SetAction(s)
	return taluo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableAction(s *string) *TeamAuditLogUpdateOne {
	if s != nil {
		taluo.SetAction(*s)
	}
	return taluo
}

// SetTargetType sets the "target_type" field.
func (taluo *TeamAuditLogUpdateOne) SetTargetType(s string) *TeamAuditLogUpdateOne {
	taluo.mutation.SetTargetType(s)
	return taluo
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableTargetType(s *string) *TeamAuditLogUpdateOne {
	if s != nil {
		taluo.SetTargetType(*s)
	}
	return taluo
}

// SetTargetID sets the "target_id" field.
func (taluo *TeamAuditLogUpdateOne) SetTargetID(i int) *TeamAuditLogUpdateOne {
	taluo.mutation.ResetTargetID()
	taluo.mutation.SetTargetID(i)
	return taluo
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableTargetID(i *int) *TeamAuditLogUpdateOne {
	if i != nil {
		taluo.SetTargetID(*i)
	}
	return taluo
}

// AddTargetID adds i to the "target_id" field.
func (taluo *TeamAuditLogUpdateOne) AddTargetID(i int) *TeamAuditLogUpdateOne {
	taluo.mutation.AddTargetID(i)
	return taluo
}

// SetTargetName sets the "target_name" field.
func (taluo *TeamAuditLogUpdateOne) SetTargetName(s string) *TeamAuditLogUpdateOne {
	taluo.mutation.SetTargetName(s)
	return taluo
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableTargetName(s *string) *TeamAuditLogUpdateOne {
	if s != nil {
		taluo.SetTargetName(*s)
	}
	return taluo
}

// SetBefore sets the "before" field.
func (taluo *TeamAuditLogUpdateOne) SetBefore(m map[string]interface{}) *TeamAuditLogUpdateOne {
	taluo.mutation.SetBefore(m)
	return taluo
}

// ClearBefore clears the value of the "before" field.
func (taluo *TeamAuditLogUpdateOne) ClearBefore() *TeamAuditLogUpdateOne {
	taluo.mutation.ClearBefore()
	return taluo
}

// SetAfter sets the "after" field.
func (taluo *TeamAuditLogUpdateOne) SetAfter(m map[string]interface{}) *TeamAuditLogUpdateOne {
	taluo.mutation.SetAfter(m)
	return taluo
}

// ClearAfter clears the value of the "after" field.
func (taluo *TeamAuditLogUpdateOne) ClearAfter() *TeamAuditLogUpdateOne {
	taluo.mutation.ClearAfter()
	return taluo
}

// SetIP sets the "ip" field.
func (taluo *TeamAuditLogUpdateOne) SetIP(s string) *TeamAuditLogUpdateOne {
	taluo.mutation.SetIP(s)
	return taluo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableIP(s *string) *TeamAuditLogUpdateOne {
	if s != nil {
		taluo.SetIP(*s)
	}
	return taluo
}

// SetRequestID sets the "request_id" field.
func (taluo *TeamAuditLogUpdateOne) SetRequestID(s string) *TeamAuditLogUpdateOne {
	taluo.mutation.SetRequestID(s)
	return taluo
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (taluo *TeamAuditLogUpdateOne) SetNillableRequestID(s *string) *TeamAuditLogUpdateOne {
	if s != nil {
		taluo.SetRequestID(*s)
	}
	return taluo
}

// Mutation returns the TeamAuditLogMutation object of the builder.
func (taluo *TeamAuditLogUpdateOne) Mutation() *TeamAuditLogMutation {
	return taluo.mutation
}

// Where appends a list predicates to the TeamAuditLogUpdate builder.
func (taluo *TeamAuditLogUpdateOne) Where(ps ...predicate.TeamAuditLog) *TeamAuditLogUpdateOne {
	taluo.mutation.Where(ps...)
	return taluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (taluo *TeamAuditLogUpdateOne) Select(field string, fields ...string) *TeamAuditLogUpdateOne {
	taluo.fields = append([]string{field}, fields...)
	return taluo
}

// Save executes the query and returns the updated TeamAuditLog entity.
func (taluo *TeamAuditLogUpdateOne) Save(ctx context.Context) (*TeamAuditLog, error) {
	return withHooks(ctx, taluo.sqlSave, taluo.mutation, taluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (taluo *TeamAuditLogUpdateOne) SaveX(ctx context.Context) *TeamAuditLog {
	node, err := taluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (taluo *TeamAuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := taluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (taluo *TeamAuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := taluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (taluo *TeamAuditLogUpdateOne) check() error {
	if v, ok := taluo.mutation.ActorEmail(); ok {
		if err := teamauditlog.ActorEmailValidator(v); err != nil {
			return &ValidationError{Name: "actor_email", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.actor_email": %w`, err)}
		}
	}
	if v, ok := taluo.mutation.Action(); ok {
		if err := teamauditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.action": %w`, err)}
		}
	}
	if v, ok := taluo.mutation.TargetType(); ok {
		if err := teamauditlog.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.target_type": %w`, err)}
		}
	}
	if v, ok := taluo.mutation.TargetName(); ok {
		if err := teamauditlog.TargetNameValidator(v); err != nil {
			return &ValidationError{Name: "target_name", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.target_name": %w`, err)}
		}
	}
	if v, ok := taluo.mutation.IP(); ok {
		if err := teamauditlog.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.ip": %w`, err)}
		}
	}
	if v, ok := taluo.mutation.RequestID(); ok {
		if err := teamauditlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "TeamAuditLog.request_id": %w`, err)}
		}
	}
	return nil
}

func (taluo *TeamAuditLogUpdateOne) sqlSave(ctx context.Context) (_node *TeamAuditLog, err error) {
	if err := taluo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(teamauditlog.Table, teamauditlog.Columns, sqlgraph.NewFieldSpec(teamauditlog.FieldID, field.TypeInt))
	id, ok := taluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TeamAuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := taluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamauditlog.FieldID)
		for _, f := range fields {
			if !teamauditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != teamauditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := taluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := taluo.mutation.OwnerID(); ok {
		_spec.SetField(teamauditlog.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := taluo.mutation.AddedOwnerID(); ok {
		_spec.AddField(teamauditlog.FieldOwnerID, field.TypeInt, value)
	}
	if value, ok := taluo.mutation.ActorUserID(); ok {
		_spec.SetField(teamauditlog.FieldActorUserID, field.TypeInt, value)
	}
	if value, ok := taluo.mutation.AddedActorUserID(); ok {
		_spec.AddField(teamauditlog.FieldActorUserID, field.TypeInt, value)
	}
	if value, ok := taluo.mutation.ActorEmail(); ok {
		_spec.SetField(teamauditlog.FieldActorEmail, field.TypeString, value)
	}
	if value, ok := taluo.mutation.Action(); ok {
		_spec.SetField(teamauditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := taluo.mutation.TargetType(); ok {
		_spec.SetField(teamauditlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := taluo.mutation.TargetID(); ok {
		_spec.SetField(teamauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := taluo.mutation.AddedTargetID(); ok {
		_spec.AddField(teamauditlog.FieldTargetID, field.TypeInt, value)
	}
	if value, ok := taluo.mutation.TargetName(); ok {
		_spec.SetField(teamauditlog.FieldTargetName, field.TypeString, value)
	}
	if value, ok := taluo.mutation.Before(); ok {
		_spec.SetField(teamauditlog.FieldBefore, field.TypeJSON, value)
	}
	if taluo.mutation.BeforeCleared() {
		_spec.ClearField(teamauditlog.FieldBefore, field.TypeJSON)
	}
	if value, ok := taluo.mutation.After(); ok {
		_spec.SetField(teamauditlog.FieldAfter, field.TypeJSON, value)
	}
	if taluo.mutation.AfterCleared() {
		_spec.ClearField(teamauditlog.FieldAfter, field.TypeJSON)
	}
	if value, ok := taluo.mutation.IP(); ok {
		_spec.SetField(teamauditlog.FieldIP, field.TypeString, value)
	}
	if value, ok := taluo.mutation.RequestID(); ok {
		_spec.SetField(teamauditlog.FieldRequestID, field.TypeString, value)
	}
	_node = &TeamAuditLog{config: taluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, taluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{teamauditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	taluo.mutation.done = true
	return _node, nil
}
