// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/DouDOU-start/airgate-core/ent/usernotification"
)

// UserNotification is the model entity for the UserNotification schema.
type UserNotification struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 接收者 user id（普通列，无外键）。
	UserID int `json:"user_id,omitempty"`
	// 通知类型：quota_alert / balance_alert / system；前端按 kind 选图标与多语言。
	Kind string `json:"kind,omitempty"`
	// 严重程度：info 普通、warning 预警（≥80%）、danger 已用尽 / 需立即处理。
	Level usernotification.Level `json:"level,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// 控制台内跳转路径，如 /team、/usage、/profile；空表示无跳转。
	Link string `json:"link,omitempty"`
	// 去重钥匙（唯一）：同一事件只投递一次；为空表示不去重。
	DedupeKey string `json:"dedupe_key,omitempty"`
	// 已读时间；NULL 表示未读。
	ReadAt *time.Time `json:"read_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserNotification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usernotification.FieldID, usernotification.FieldUserID:
			values[i] = new(sql.NullInt64)
		case usernotification.FieldKind, usernotification.FieldLevel, usernotification.FieldTitle, usernotification.FieldContent, usernotification.FieldLink, usernotification.FieldDedupeKey:
			values[i] = new(sql.NullString)
		case usernotification.FieldReadAt, usernotification.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserNotification fields.
func (un *UserNotification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usernotification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			un.ID = int(value.Int64)
		case usernotification.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				un.UserID = int(value.Int64)
			}
		case usernotification.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				un.Kind = value.String
			}
		case usernotification.FieldLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field level", values[i])
			} else if value.Valid {
				un.Level = usernotification.Level(value.String)
			}
		case usernotification.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				un.Title = value.String
			}
		case usernotification.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				un.Content = value.String
			}
		case usernotification.FieldLink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field link", values[i])
			} else if value.Valid {
				un.Link = value.String
			}
		case usernotification.FieldDedupeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dedupe_key", values[i])
			} else if value.Valid {
				un.DedupeKey = value.String
			}
		case usernotification.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				un.ReadAt = new(time.Time)
				*un.ReadAt = value.Time
			}
		case usernotification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				un.CreatedAt = value.Time
			}
		default:
			un.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserNotification.
// This includes values selected through modifiers, order, etc.
func (un *UserNotification) Value(name string) (ent.Value, error) {
	return un.selectValues.Get(name)
}

// Update returns a builder for updating this UserNotification.
// Note that you need to call UserNotification.Unwrap() before calling this method if this UserNotification
// was returned from a transaction, and the transaction was committed or rolled back.
func (un *UserNotification) Update() *UserNotificationUpdateOne {
	return NewUserNotificationClient(un.config).UpdateOne(un)
}

// Unwrap unwraps the UserNotification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (un *UserNotification) Unwrap() *UserNotification {
	_tx, ok := un.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserNotification is not a transactional entity")
	}
	un.config.driver = _tx.drv
	return un
}

// String implements the fmt.Stringer.
func (un *UserNotification) String() string {
	var builder strings.Builder
	builder.WriteString("UserNotification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", un.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", un.UserID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(un.Kind)
	builder.WriteString(", ")
	builder.WriteString("level=")
	builder.WriteString(fmt.Sprintf("%v", un.Level))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(un.Title)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(un.Content)
	builder.WriteString(", ")
	builder.WriteString("link=")
	builder.WriteString(un.Link)
	builder.WriteString(", ")
	builder.WriteString("dedupe_key=")
	builder.WriteString(un.DedupeKey)
	builder.WriteString(", ")
	if v := un.ReadAt; v != nil {
		builder.WriteString("read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(un.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserNotifications is a parsable slice of UserNotification.
type UserNotifications []*UserNotification
