// Code generated by ent, DO NOT EDIT.

package apikey

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldName, v))
}

// KeyHint applies equality check predicate on the "key_hint" field. It's identical to KeyHintEQ.
func KeyHint(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyHint, v))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyEncrypted applies equality check predicate on the "key_encrypted" field. It's identical to KeyEncryptedEQ.
func KeyEncrypted(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyEncrypted, v))
}

// QuotaUsd applies equality check predicate on the "quota_usd" field. It's identical to QuotaUsdEQ.
func QuotaUsd(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldQuotaUsd, v))
}

// UsedQuota applies equality check predicate on the "used_quota" field. It's identical to UsedQuotaEQ.
func UsedQuota(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldUsedQuota, v))
}

// UsedQuotaActual applies equality check predicate on the "used_quota_actual" field. It's identical to UsedQuotaActualEQ.
func UsedQuotaActual(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldUsedQuotaActual, v))
}

// SellRate applies equality check predicate on the "sell_rate" field. It's identical to SellRateEQ.
func SellRate(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldSellRate, v))
}

// MaxConcurrency applies equality check predicate on the "max_concurrency" field. It's identical to MaxConcurrencyEQ.
func MaxConcurrency(v int) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldMaxConcurrency, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContainsFold(FieldName, v))
}

// KeyHintEQ applies the EQ predicate on the "key_hint" field.
func KeyHintEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyHint, v))
}

// KeyHintNEQ applies the NEQ predicate on the "key_hint" field.
func KeyHintNEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldKeyHint, v))
}

// KeyHintIn applies the In predicate on the "key_hint" field.
func KeyHintIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldKeyHint, vs...))
}

// KeyHintNotIn applies the NotIn predicate on the "key_hint" field.
func KeyHintNotIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldKeyHint, vs...))
}

// KeyHintGT applies the GT predicate on the "key_hint" field.
func KeyHintGT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldKeyHint, v))
}

// KeyHintGTE applies the GTE predicate on the "key_hint" field.
func KeyHintGTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldKeyHint, v))
}

// KeyHintLT applies the LT predicate on the "key_hint" field.
func KeyHintLT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldKeyHint, v))
}

// KeyHintLTE applies the LTE predicate on the "key_hint" field.
func KeyHintLTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldKeyHint, v))
}

// KeyHintContains applies the Contains predicate on the "key_hint" field.
func KeyHintContains(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContains(FieldKeyHint, v))
}

// KeyHintHasPrefix applies the HasPrefix predicate on the "key_hint" field.
func KeyHintHasPrefix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasPrefix(FieldKeyHint, v))
}

// KeyHintHasSuffix applies the HasSuffix predicate on the "key_hint" field.
func KeyHintHasSuffix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasSuffix(FieldKeyHint, v))
}

// KeyHintEqualFold applies the EqualFold predicate on the "key_hint" field.
func KeyHintEqualFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEqualFold(FieldKeyHint, v))
}

// KeyHintContainsFold applies the ContainsFold predicate on the "key_hint" field.
func KeyHintContainsFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContainsFold(FieldKeyHint, v))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldKeyHash, v))
}

// KeyHashContains applies the Contains predicate on the "key_hash" field.
func KeyHashContains(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContains(FieldKeyHash, v))
}

// KeyHashHasPrefix applies the HasPrefix predicate on the "key_hash" field.
func KeyHashHasPrefix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasPrefix(FieldKeyHash, v))
}

// KeyHashHasSuffix applies the HasSuffix predicate on the "key_hash" field.
func KeyHashHasSuffix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasSuffix(FieldKeyHash, v))
}

// KeyHashEqualFold applies the EqualFold predicate on the "key_hash" field.
func KeyHashEqualFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEqualFold(FieldKeyHash, v))
}

// KeyHashContainsFold applies the ContainsFold predicate on the "key_hash" field.
func KeyHashContainsFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContainsFold(FieldKeyHash, v))
}

// KeyEncryptedEQ applies the EQ predicate on the "key_encrypted" field.
func KeyEncryptedEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldKeyEncrypted, v))
}

// KeyEncryptedNEQ applies the NEQ predicate on the "key_encrypted" field.
func KeyEncryptedNEQ(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldKeyEncrypted, v))
}

// KeyEncryptedIn applies the In predicate on the "key_encrypted" field.
func KeyEncryptedIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldKeyEncrypted, vs...))
}

// KeyEncryptedNotIn applies the NotIn predicate on the "key_encrypted" field.
func KeyEncryptedNotIn(vs ...string) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldKeyEncrypted, vs...))
}

// KeyEncryptedGT applies the GT predicate on the "key_encrypted" field.
func KeyEncryptedGT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldKeyEncrypted, v))
}

// KeyEncryptedGTE applies the GTE predicate on the "key_encrypted" field.
func KeyEncryptedGTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldKeyEncrypted, v))
}

// KeyEncryptedLT applies the LT predicate on the "key_encrypted" field.
func KeyEncryptedLT(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldKeyEncrypted, v))
}

// KeyEncryptedLTE applies the LTE predicate on the "key_encrypted" field.
func KeyEncryptedLTE(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldKeyEncrypted, v))
}

// KeyEncryptedContains applies the Contains predicate on the "key_encrypted" field.
func KeyEncryptedContains(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContains(FieldKeyEncrypted, v))
}

// KeyEncryptedHasPrefix applies the HasPrefix predicate on the "key_encrypted" field.
func KeyEncryptedHasPrefix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasPrefix(FieldKeyEncrypted, v))
}

// KeyEncryptedHasSuffix applies the HasSuffix predicate on the "key_encrypted" field.
func KeyEncryptedHasSuffix(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldHasSuffix(FieldKeyEncrypted, v))
}

// KeyEncryptedIsNil applies the IsNil predicate on the "key_encrypted" field.
func KeyEncryptedIsNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldIsNull(FieldKeyEncrypted))
}

// KeyEncryptedNotNil applies the NotNil predicate on the "key_encrypted" field.
func KeyEncryptedNotNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldNotNull(FieldKeyEncrypted))
}

// KeyEncryptedEqualFold applies the EqualFold predicate on the "key_encrypted" field.
func KeyEncryptedEqualFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldEqualFold(FieldKeyEncrypted, v))
}

// KeyEncryptedContainsFold applies the ContainsFold predicate on the "key_encrypted" field.
func KeyEncryptedContainsFold(v string) predicate.APIKey {
	return predicate.APIKey(sql.FieldContainsFold(FieldKeyEncrypted, v))
}

// IPWhitelistIsNil applies the IsNil predicate on the "ip_whitelist" field.
func IPWhitelistIsNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldIsNull(FieldIPWhitelist))
}

// IPWhitelistNotNil applies the NotNil predicate on the "ip_whitelist" field.
func IPWhitelistNotNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldNotNull(FieldIPWhitelist))
}

// IPBlacklistIsNil applies the IsNil predicate on the "ip_blacklist" field.
func IPBlacklistIsNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldIsNull(FieldIPBlacklist))
}

// IPBlacklistNotNil applies the NotNil predicate on the "ip_blacklist" field.
func IPBlacklistNotNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldNotNull(FieldIPBlacklist))
}

// QuotaUsdEQ applies the EQ predicate on the "quota_usd" field.
func QuotaUsdEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldQuotaUsd, v))
}

// QuotaUsdNEQ applies the NEQ predicate on the "quota_usd" field.
func QuotaUsdNEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldQuotaUsd, v))
}

// QuotaUsdIn applies the In predicate on the "quota_usd" field.
func QuotaUsdIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldQuotaUsd, vs...))
}

// QuotaUsdNotIn applies the NotIn predicate on the "quota_usd" field.
func QuotaUsdNotIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldQuotaUsd, vs...))
}

// QuotaUsdGT applies the GT predicate on the "quota_usd" field.
func QuotaUsdGT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldQuotaUsd, v))
}

// QuotaUsdGTE applies the GTE predicate on the "quota_usd" field.
func QuotaUsdGTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldQuotaUsd, v))
}

// QuotaUsdLT applies the LT predicate on the "quota_usd" field.
func QuotaUsdLT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldQuotaUsd, v))
}

// QuotaUsdLTE applies the LTE predicate on the "quota_usd" field.
func QuotaUsdLTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldQuotaUsd, v))
}

// UsedQuotaEQ applies the EQ predicate on the "used_quota" field.
func UsedQuotaEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldUsedQuota, v))
}

// UsedQuotaNEQ applies the NEQ predicate on the "used_quota" field.
func UsedQuotaNEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldUsedQuota, v))
}

// UsedQuotaIn applies the In predicate on the "used_quota" field.
func UsedQuotaIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldUsedQuota, vs...))
}

// UsedQuotaNotIn applies the NotIn predicate on the "used_quota" field.
func UsedQuotaNotIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldUsedQuota, vs...))
}

// UsedQuotaGT applies the GT predicate on the "used_quota" field.
func UsedQuotaGT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldUsedQuota, v))
}

// UsedQuotaGTE applies the GTE predicate on the "used_quota" field.
func UsedQuotaGTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldUsedQuota, v))
}

// UsedQuotaLT applies the LT predicate on the "used_quota" field.
func UsedQuotaLT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldUsedQuota, v))
}

// UsedQuotaLTE applies the LTE predicate on the "used_quota" field.
func UsedQuotaLTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldUsedQuota, v))
}

// UsedQuotaActualEQ applies the EQ predicate on the "used_quota_actual" field.
func UsedQuotaActualEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldUsedQuotaActual, v))
}

// UsedQuotaActualNEQ applies the NEQ predicate on the "used_quota_actual" field.
func UsedQuotaActualNEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldUsedQuotaActual, v))
}

// UsedQuotaActualIn applies the In predicate on the "used_quota_actual" field.
func UsedQuotaActualIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldUsedQuotaActual, vs...))
}

// UsedQuotaActualNotIn applies the NotIn predicate on the "used_quota_actual" field.
func UsedQuotaActualNotIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldUsedQuotaActual, vs...))
}

// UsedQuotaActualGT applies the GT predicate on the "used_quota_actual" field.
func UsedQuotaActualGT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldUsedQuotaActual, v))
}

// UsedQuotaActualGTE applies the GTE predicate on the "used_quota_actual" field.
func UsedQuotaActualGTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldUsedQuotaActual, v))
}

// UsedQuotaActualLT applies the LT predicate on the "used_quota_actual" field.
func UsedQuotaActualLT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldUsedQuotaActual, v))
}

// UsedQuotaActualLTE applies the LTE predicate on the "used_quota_actual" field.
func UsedQuotaActualLTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldUsedQuotaActual, v))
}

// SellRateEQ applies the EQ predicate on the "sell_rate" field.
func SellRateEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldSellRate, v))
}

// SellRateNEQ applies the NEQ predicate on the "sell_rate" field.
func SellRateNEQ(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldSellRate, v))
}

// SellRateIn applies the In predicate on the "sell_rate" field.
func SellRateIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldSellRate, vs...))
}

// SellRateNotIn applies the NotIn predicate on the "sell_rate" field.
func SellRateNotIn(vs ...float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldSellRate, vs...))
}

// SellRateGT applies the GT predicate on the "sell_rate" field.
func SellRateGT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldSellRate, v))
}

// SellRateGTE applies the GTE predicate on the "sell_rate" field.
func SellRateGTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldSellRate, v))
}

// SellRateLT applies the LT predicate on the "sell_rate" field.
func SellRateLT(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldSellRate, v))
}

// SellRateLTE applies the LTE predicate on the "sell_rate" field.
func SellRateLTE(v float64) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldSellRate, v))
}

// MaxConcurrencyEQ applies the EQ predicate on the "max_concurrency" field.
func MaxConcurrencyEQ(v int) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyNEQ applies the NEQ predicate on the "max_concurrency" field.
func MaxConcurrencyNEQ(v int) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldMaxConcurrency, v))
}

// MaxConcurrencyIn applies the In predicate on the "max_concurrency" field.
func MaxConcurrencyIn(vs ...int) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyNotIn applies the NotIn predicate on the "max_concurrency" field.
func MaxConcurrencyNotIn(vs ...int) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldMaxConcurrency, vs...))
}

// MaxConcurrencyGT applies the GT predicate on the "max_concurrency" field.
func MaxConcurrencyGT(v int) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldMaxConcurrency, v))
}

// MaxConcurrencyGTE applies the GTE predicate on the "max_concurrency" field.
func MaxConcurrencyGTE(v int) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldMaxConcurrency, v))
}

// MaxConcurrencyLT applies the LT predicate on the "max_concurrency" field.
func MaxConcurrencyLT(v int) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldMaxConcurrency, v))
}

// MaxConcurrencyLTE applies the LTE predicate on the "max_concurrency" field.
func MaxConcurrencyLTE(v int) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldMaxConcurrency, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.APIKey {
	return predicate.APIKey(sql.FieldNotNull(FieldExpiresAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldStatus, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKey {
	return predicate.APIKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMember applies the HasEdge predicate on the "member" edge.
func HasMember() predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemberTable, MemberColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemberWith applies the HasEdge predicate on the "member" edge with a given conditions (other predicates).
func HasMemberWith(preds ...predicate.Member) predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := newMemberStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.APIKey {
	return predicate.APIKey(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKey) predicate.APIKey {
	return predicate.APIKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKey) predicate.APIKey {
	return predicate.APIKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKey) predicate.APIKey {
	return predicate.APIKey(sql.NotPredicates(p))
}
