// Code generated by ent, DO NOT EDIT.

package usersubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/DouDOU-start/airgate-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldID, id))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldEffectiveAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldExpiresAt, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldPeriodEnd, v))
}

// CreditsUsed applies equality check predicate on the "credits_used" field. It's identical to CreditsUsedEQ.
func CreditsUsed(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldCreditsUsed, v))
}

// ExtraCredits applies equality check predicate on the "extra_credits" field. It's identical to ExtraCreditsEQ.
func ExtraCredits(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldExtraCredits, v))
}

// ImagesUsed applies equality check predicate on the "images_used" field. It's identical to ImagesUsedEQ.
func ImagesUsed(v int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldImagesUsed, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldEffectiveAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldExpiresAt, v))
}

// UsageIsNil applies the IsNil predicate on the "usage" field.
func UsageIsNil() predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIsNull(FieldUsage))
}

// UsageNotNil applies the NotNil predicate on the "usage" field.
func UsageNotNil() predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotNull(FieldUsage))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldStatus, vs...))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodStartIsNil applies the IsNil predicate on the "period_start" field.
func PeriodStartIsNil() predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIsNull(FieldPeriodStart))
}

// PeriodStartNotNil applies the NotNil predicate on the "period_start" field.
func PeriodStartNotNil() predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotNull(FieldPeriodStart))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldPeriodEnd, v))
}

// PeriodEndIsNil applies the IsNil predicate on the "period_end" field.
func PeriodEndIsNil() predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIsNull(FieldPeriodEnd))
}

// PeriodEndNotNil applies the NotNil predicate on the "period_end" field.
func PeriodEndNotNil() predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotNull(FieldPeriodEnd))
}

// CreditsUsedEQ applies the EQ predicate on the "credits_used" field.
func CreditsUsedEQ(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldCreditsUsed, v))
}

// CreditsUsedNEQ applies the NEQ predicate on the "credits_used" field.
func CreditsUsedNEQ(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldCreditsUsed, v))
}

// CreditsUsedIn applies the In predicate on the "credits_used" field.
func CreditsUsedIn(vs ...float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldCreditsUsed, vs...))
}

// CreditsUsedNotIn applies the NotIn predicate on the "credits_used" field.
func CreditsUsedNotIn(vs ...float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldCreditsUsed, vs...))
}

// CreditsUsedGT applies the GT predicate on the "credits_used" field.
func CreditsUsedGT(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldCreditsUsed, v))
}

// CreditsUsedGTE applies the GTE predicate on the "credits_used" field.
func CreditsUsedGTE(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldCreditsUsed, v))
}

// CreditsUsedLT applies the LT predicate on the "credits_used" field.
func CreditsUsedLT(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldCreditsUsed, v))
}

// CreditsUsedLTE applies the LTE predicate on the "credits_used" field.
func CreditsUsedLTE(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldCreditsUsed, v))
}

// ExtraCreditsEQ applies the EQ predicate on the "extra_credits" field.
func ExtraCreditsEQ(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldExtraCredits, v))
}

// ExtraCreditsNEQ applies the NEQ predicate on the "extra_credits" field.
func ExtraCreditsNEQ(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldExtraCredits, v))
}

// ExtraCreditsIn applies the In predicate on the "extra_credits" field.
func ExtraCreditsIn(vs ...float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldExtraCredits, vs...))
}

// ExtraCreditsNotIn applies the NotIn predicate on the "extra_credits" field.
func ExtraCreditsNotIn(vs ...float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldExtraCredits, vs...))
}

// ExtraCreditsGT applies the GT predicate on the "extra_credits" field.
func ExtraCreditsGT(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldExtraCredits, v))
}

// ExtraCreditsGTE applies the GTE predicate on the "extra_credits" field.
func ExtraCreditsGTE(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldExtraCredits, v))
}

// ExtraCreditsLT applies the LT predicate on the "extra_credits" field.
func ExtraCreditsLT(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldExtraCredits, v))
}

// ExtraCreditsLTE applies the LTE predicate on the "extra_credits" field.
func ExtraCreditsLTE(v float64) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldExtraCredits, v))
}

// ImagesUsedEQ applies the EQ predicate on the "images_used" field.
func ImagesUsedEQ(v int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldImagesUsed, v))
}

// ImagesUsedNEQ applies the NEQ predicate on the "images_used" field.
func ImagesUsedNEQ(v int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldImagesUsed, v))
}

// ImagesUsedIn applies the In predicate on the "images_used" field.
func ImagesUsedIn(vs ...int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldImagesUsed, vs...))
}

// ImagesUsedNotIn applies the NotIn predicate on the "images_used" field.
func ImagesUsedNotIn(vs ...int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldImagesUsed, vs...))
}

// ImagesUsedGT applies the GT predicate on the "images_used" field.
func ImagesUsedGT(v int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldImagesUsed, v))
}

// ImagesUsedGTE applies the GTE predicate on the "images_used" field.
func ImagesUsedGTE(v int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldImagesUsed, v))
}

// ImagesUsedLT applies the LT predicate on the "images_used" field.
func ImagesUsedLT(v int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldImagesUsed, v))
}

// ImagesUsedLTE applies the LTE predicate on the "images_used" field.
func ImagesUsedLTE(v int) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldImagesUsed, v))
}

// BillingCycleEQ applies the EQ predicate on the "billing_cycle" field.
func BillingCycleEQ(v BillingCycle) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldBillingCycle, v))
}

// BillingCycleNEQ applies the NEQ predicate on the "billing_cycle" field.
func BillingCycleNEQ(v BillingCycle) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldBillingCycle, v))
}

// BillingCycleIn applies the In predicate on the "billing_cycle" field.
func BillingCycleIn(vs ...BillingCycle) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldBillingCycle, vs...))
}

// BillingCycleNotIn applies the NotIn predicate on the "billing_cycle" field.
func BillingCycleNotIn(vs ...BillingCycle) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldBillingCycle, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserSubscription {
	return predicate.UserSubscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserSubscription {
	return predicate.UserSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserSubscription {
	return predicate.UserSubscription(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.UserSubscription {
	return predicate.UserSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.UserSubscription {
	return predicate.UserSubscription(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserSubscription) predicate.UserSubscription {
	return predicate.UserSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserSubscription) predicate.UserSubscription {
	return predicate.UserSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserSubscription) predicate.UserSubscription {
	return predicate.UserSubscription(sql.NotPredicates(p))
}
